- code/modules/power/fusion_engine.dm
Изменил потребление заряда стержней в генераторах корабля
Если в стержнях меньше 10%, то 0.1 > 0.2
Если в стержнях меньше 50%, то 0.5 > 0.8
Работа для шиптехов, стержни требуют обслуживания чаще 1 раза за раунд
:cl:
balance: повышено потребление заряда стержней в генераторах корабля
/:cl:
>  Increasing energy consumption from ship rods

- code/__HELPERS/ai.dm
- code/_globalvars/lists/mobs.dm
- code/game/objects/items/motion_detector.dm
- code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
- code/modules/projectiles/sentries.dm
Обычная стелс атака теперь имеет 15 ап, с маскировкой 25.
Паунс с готовой стелс атакой теперь работает, и наносит обычный дополнительный урон.
Детекторы "движения" теперь игнорируют стелс хантера и химеры.
Турели и детекторы движения теперь реагируют на миражи.
Скорость миражей теперь случайно варьируется, чтобы было легче между ними спрятаться.
Скорость атаки миражей также теперь случайно варьируется, чтобы они не били одновременно. Также поправил то что они били вне ренжа атаки.
Мёртвая каста.
```
:cl:
add: Миражи хантера теперь чуть-чуть реалистичнее. И на них реагируют детекторы движения и турели.
balance: Детекторы движения теперь игнорят стелс хантера и химеры.
balance: Скрытые атаки хантера теперь имеют немного АП.
fix: Паунс с готовой стелс атакой теперь работает.
fix: Миражи …
```
> Makes hunter mirages more convincing, motion detectors now ignore xenos in stealth, adds some ap to hunter's stealth attacks.

- code/modules/codex/entries/ammunition_codex.dm
- code/modules/codex/entries/magazine_codex.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/projectile.dm
Механика дополнительного ап применяемое к ксеноморфам
```
:cl:
add: additionak xeno penetration ammo
/:cl:
```
> Xeno penetration

- code/game/objects/items/reagent_containers/hypospray.dm
- code/game/objects/items/reagent_containers/reagent_container.dm
- code/game/objects/items/stacks/medical.dm
частичный порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/16072
```
:cl:
qol: Using medical items in-hand will now apply them to yourself
/:cl:
```
> Medical items now apply to yourself if you use them in-hand

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/client/preferences_ui.dm
Порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/15975
> Ports keybindings fixes.

- code/game/turfs/space/transit.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
```
:cl:
fix: Мобы теперь не падают с неба дважды, если пошли против направления потока космоса.
/:cl:
```
> Few fixes to the sky diving.

- code/__DEFINES/conflict.dm
- code/__DEFINES/mobs.dm
- code/game/data_huds.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/carbon/xenomorph/life.dm
- code/modules/mob/living/carbon/xenomorph/update_icons.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/living/living_health_procs.dm
- code/modules/predator/yautja/weapons/ranged.dm
- code/modules/projectiles/guns/specialist.dm
https://github.com/tgstation/TerraGov-Marine-Corps/pull/14878
Ксеновская реген сила теперь отображается во вкладке статуса.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/15112
Ксеновские и человеческие слои оверлеев объединенны в один.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/15167
Исправлено то что включенные феромоны не тратили 5 плазмы в тик.
Оптимизировано использование `hud_set_plasma()` чтобы его не вызывало несколько раз в тик. Вместо этого плазма теперь обновляется только спец. проками, а плазма худ обновляется только после числа плазмы.
Optimises the use of hud_set_plasma() so its not getting called multiple times every life tick and other random times. Instead, plasma is now only updated by the setter procs, and plasma hud is only updated when plasma …
> Ports 14878, 15112, 15167

- code/datums/components/bump_attack.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/silicon/ai/ai_verbs.dm
Ксеносы более не могут меняться с местами с намертво зафиксированными людьми, как с камнем Кинга например.
ИИ теперь можно полноценно тащить когда они снимает болты.
Ксеносы теперь толкают людей при бамп атаке только в дизарм интенте.
https://github.com/user-attachments/assets/00365056-858f-4154-8e67-7db968d2c53e
Вещи работают как должны.
Меньше говна по-типу своппа окаменелых маринов под тад.
Толкание людей от себя, когда тебе это не нужно, ощутимо фрустрирует.
```
:cl:
add: Ксеносы при бамп аттаках теперь толкают людей только в дизарм интенте.
balance: Ксеносы теперь не могут меняться местами с людьми в камне Кинга, и прочих условиях в которых они намертво обездвижены.
fix: ИИ теперь можно нормально тащить если он снимет болты.
code: Немного переделал код своппа местами.
/:cl:
```
> Movement fixes and adjustments.

- code/__DEFINES/mobs.dm
- code/__DEFINES/movement.dm
- code/modules/mob/mob_movement.dm
Поменял движение на более "тгшное"
Диагональное движение должно стать плавнее, и должны убраться рывки при движении при малой скорости
```
:cl:
add: smooth glide
/:cl:
```
> Movement glide

- code/game/objects/items/motion_detector.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
Убрал шизу спагетти, МОУШЕН детектор это МОУШЕН детектор
минус вх
https://www.youtube.com/watch?v=1t5R_LMfIi0
```
:cl:
add: motion sensor move check
/:cl:
```
> Motion sensor

- code/_onclick/hud/fullscreen.dm
- code/game/objects/machinery/computer/computer.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures/reagent_dispensers.dm
- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
- code/modules/mob/living/simple_animal/friendly/parrot.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/projectiles/gun_system.dm
- code/modules/projectiles/projectile.dm
- code/modules/vehicles/atv.dm
- code/modules/vehicles/mecha/mecha_defense.dm
Порт пр-ов с оффов.
Сообщения от попадания пули для чата не генерируются, если не будут использованы в дальнейшем.
Фуллскрин оверлеи теперь удаляются по таймеру, который при появлении новых оверлеев обновляется.
Меньше лагов, наверное
> Fullscreen overlays and chat bullet act message cleanup

- code/game/objects/machinery/vending/marine_vending.dm
- code/game/objects/machinery/vending/vending.dm
- code/game/objects/machinery/vending/vending_types.dm
- tgui/packages/tgui/interfaces/Vending.tsx
Удалил интеракции с деньгами и айди картой для "оплаты", так как они совершенно ничего не делают, а привязку к личным поинтам если нам когда-нибудь захочется такую хуйню сделать, можно будет и по-нормальному.
Теперь можно будет покупать напитки из вендора с напитками, без страданий из-за говнокода.
```
:cl:
qol: Вендор с газированными напитками теперь можно нормально использовать.
/:cl:
```
> Delete prices and money interactions for vendors.

- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/game/objects/structures/crates_lockers/walllocker.dm
Шкафы теперь открываются и закрываются также как на ТГ.
То-есть на ЛКМ ты, если шкаф заблокирован - разблокируешь его, потом открываешь-закрываешь.
На ПКМ ты, если шкаф открыт - то закрываешь, и уже потом блокируешь-разблокируешь.
В разы удобней чем тыкать предметами, или контр-интуитивным альт-кликом.
```
:cl:
qol: Шкафы теперь открываются на ЛКМ, закрываются на ПКМ, вместо альт-клика и тыканья предметами.
/:cl:
```
> Locker qol and a little cleanup.

- code/modules/mob/living/carbon/xenomorph/update_icons.dm
Теперь без вот этого:
Удобство
```
:cl: Оверлеи ран и огня теперь не отображаются в шифт-пкм.
fix: Исправил некоторые вещи.
/:cl:
```
> Xeno wound and fire overlays now have `vis_inherit_id` flag

- code/game/objects/structures/prop.dm
Заборчики вокруг Нормандии на Талосе теперь непроходимы, но их можно перепрыгнуть, перелезть или сломать.
Заборчики не будут как пустая декорация.
```
:cl:
add: Заборчики на Талосе вокруг Нормандии теперь твердые, но их можно перелезть, перепрыгнуть или сломать.
/:cl:
```
> Makes railings on talos dense.

- code/game/objects/items/storage/bags.dm
- code/game/objects/items/storage/storage.dm
Если контейнер лежит на полу и нажать ПКМ, то он откроется. Ранее было на альт-пкм, но блять об этом даже никто не знает.
Если перевести контейнер на пол, то ты выкинешь его содержимое на пол, если перевести на другой контейнер то он переместит содержимое в него.
Удобство.
```
:cl:
qol: ПКМ на контейнер на полу, открывает контейнер.
qol: Перетаскивание контейнера на пол, вытаскивает содержимое на него. Если перетаскивать на контейнер, то ты переместишь содержимое из одного контейнера в другой.
/:cl:
```
> Storage qols

- code/modules/mob/living/living.dm
Ксеносы блочат маров по диагоналли.
Лабиринты имеют смысл.
```
:cl:
balance: Ксеносы блочат по диагонали.
/:cl:
```
> Xenos once again block marines diagonally.

- code/modules/reagents/reagents/medical.dm
Бихексаджулин при передозе теперь ломает конечности не поочередно а при шансе в 15%.
Инапровалин больше не вешает 40 секунд сна при передозе (какой еблан это придумал), а лишь от 0.5 до 2.5 секунд сна с шансом в 15%
Меньше пидорской хуйни в билде.
```
:cl:
balance: Передоз бихексаджулина теперь ломает кости с шансом в 15%, а не гарантированно
balance: Передоз инапровалина теперь вешает 0.5 - 2.5 секунд сна с шансом в 15% вместо 40 секунд сна.
/:cl:
```
> Nerfs bihexajuline and inaprovaline ods

- code/game/objects/items/storage/storage.dm
Теперь нельзя открыть контейнер если ты ксенос, а поместить туда можно только хаггеров (в качестве ловушек)
```
:cl:
fix: Ксеносы более не могут открывать контейнеры.
/:cl:
```
> Restricts xenos from opening storages with items.

- code/game/objects/items/stacks/medical.dm
- code/modules/radial/radial_body_select.dm
Можно было открыть радиал медикал меню, положить предмет и уже без предмета в руке использовать предмет.
Как заставить радиал меню закрыться без предмета в руке я не разобрался.
```
:cl:
fix: Больше нельзя использовать медикал радиал меню для лечения без предмета в руке.
/:cl:
```
> Fixes that you could use radial medical menu to use non-present in-hand items on someone.

- code/__DEFINES/dcs/signals.dm
- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
- code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Тентакля дефайлера теперь бросает не на тайл с дефайлеров, а перед ним.
Дефайлер теперь  размером с обычного ксеноса и опять может лезть в венты.
Исправлен вдова момент.
Дефайлер не тянет на танка со своими хп и бронёй, и игнор к кнокдавну всяких слагов по-моему в разы хуже, чем возможность залезть в венты.
```
:cl:
balance: Тентакля Дефайлера теперь кидает жертву не на тайл с дефайлером, а перед ним.
balance: Дефайлер теперь меньше и может лезть в вентиляцию. 
fix: Исправлен вдова момент. Мне лень его рассписывать.
/:cl:
```
> Defiler tweaks and double attack signals sending fix.

- code/__DEFINES/traits.dm
- code/_globalvars/lists/mobs.dm
- code/_globalvars/misc.dm
- code/modules/codex/entries/mobs_codex.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
- code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
- code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
- code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
- code/modules/mob/living/carbon/xenomorph/evo_datum.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Теперь можно эволвить из любой касты в касту следующего тира.
Теперь можно менять касты своего тира раз в 15 минут.
Теперь на фазе подготовки всем с кислотой выдается сильная кислота.
Удобство.
```
:cl:
add: Теперь можно эволюционировать в любую касту следующего тира.
add: Теперь у всех ксеносов с кислотой на стадии подготовки сильная кислота.
add: Добавлена смена касты своего тира раз в 15.
/:cl:
```
> Evolution now doesn't rely on caste, adds casteswap, adds strong acid for everyone on prep phase.

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Изменена формула силы рейджа чтобы быть более плавной
СР вырезан, теперь дреин слеш работает всегда и скалируется от силы рейджа
```
:cl:
add: rage rework
/:cl:
```
> rage rework

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/living.dm
Разделил часть в коде бампа, отвечающую за смену местами между мобами, на отдельные для людей и ксеносов. Читаемость как я надеюсь возросла, хоть и ценой небольшой копипасты.
Также проверка на диагональ теперь идёт первее проверок на свап, и потому при проходе по диагонали между ними, ты их не подвинешь.
```
:cl:
fix: Проход по диагонали между мобами теперь не меняет их местами с тобой.
/:cl:
```
> Increases sanity of mob swapping checks.

- code/game/objects/items/reagent_containers/hypospray.dm
- code/game/objects/items/storage/firstaid.dm
- code/game/objects/items/storage/storage.dm
Вернул Альт-ПКМ для контейнеров.
Перенёс растворение таблеток из таблетницы гипоспреем на уровень `attackby` чтобы оно работало корректно.
```
:cl:
fix: Возвращено открытие контейнеров на альт-пкм.
fix: Взаимодействие гипоспрея с таблетницами теперь работает как должно.
/:cl:
```
> Re-adds alt-rmb for storages, moves hypospray and pill bottle interaction to attackby.

- code/modules/reqs/supplypacks.dm
Обычные щипцы теперь стоят 125 вместо 200
Улучшенные 250 вместо 120.
Логичность.
```
:cl:
fix: Цена обычных щипцов и улучшенных в карго поменяны местами.
/:cl:
```
> Swaps cargo prices of tweezers and advanced tweezers.

- code/modules/clothing/modular_armor/attachments/storage.dm
- code/modules/clothing/shoes/marine_shoes.dm
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/297 <--
легендарный бафф ботинок о котором никто не просил, становится лучше с годами как вино
> Boots buff

- code/__DEFINES/action.dm
- code/datums/actions/ability_actions.dm
- code/game/objects/effects/countdown.dm
Порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/14802
> Ability Cooldown Timers

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
резиновые хагеры теперь не самоубиваются, но срут резиной 1 раз
https://github.com/user-attachments/assets/ac5b784a-647c-4fbd-8013-ad68f10369d9
> Resin hugger buff

- code/modules/clothing/glasses/night.dm
Забыл дать им переключаемость когда рефакторил.
```
:cl:
fix: ПНВ BE-35 and BE-47 теперь переключаемы.
/:cl:
```
> Fixes BE-35 and BE-47 night vision goggles.

- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/predalien/castedatum_predalien.dm
- code/modules/projectiles/ammo_datums/xeno.dm
за место убранного нейроплевка добавил токсик сплеш, который не вводит нейро, но наносит урон токсом
плевку резиной увеличил стамин урон
пофиксил баг с двойным префиксом у абоминации
мейк претор грейт аген? не уверен
> Praetorian toxin splash

- code/__DEFINES/loadout.dm
- code/modules/reagents/reactions/medical.dm
Добавил в вендоры с поинтами монеты которые можно продать в карго за поинты, но напрямую снарягу брать должно быть всё равно выгоднее. Марины раундстарт скидываются чтобы купить б18? ДА!! Вальхалла? тоже да!
добавил лемолин медикам и синту, кому надо смеси варить тот пусть варит
немного поменял рецепты МД и сино чтобы соответствовать балансу
> Vendor coins

- code/datums/components/attachment_handler.dm
- code/modules/clothing/modular_armor/attachments.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/carbon/xenomorph/update_icons.dm
- code/modules/mob/update_icons.dm
Плащи, камы, разгрузки и прочая ересь больше не будет цеплять свой оверлей при поднятии в руки.
Также почистил код от ненужного хлама.
```
:cl:
fix: Плащи, камы, разгрузки и прочий подобный хлам больше не будут цеплять свои оверлеи при нахождении в руках.
/:cl:
```
> Fixes attachment handlers applying overlays while inhand.

- code/__DEFINES/loadout.dm
- code/game/objects/machinery/research.dm
- tgui/packages/tgui/interfaces/MarineSelector.js
Добавил нормальные названия и описания монеткам.
Также изменил категорию в вендоре.
Нормальные описания.
```
:cl:
spellcheck: Добавлены нормальные названия и описания монеткам из ресерча.
/:cl:
```
> Changed names and descriptions of credit coins.

- code/datums/gamemodes/_game_mode.dm
Створки теперь автоматически откроются на 22 минуте вместо 32 минуты
Запрет на высадку снимается на 10 минуте вместо 15 минуты
> Ускорение начала игры

- code/modules/projectiles/attachables/_attachable.dm
При отсоединении прицелов дающих прицеливание, при включенном прицеливании больше не будет даваться прицеливание без возможности выключить.
```
:cl:
fix: Отсоединение прицелов дающих аим мод теперь отключает его если он был включен.
/:cl:
```
> Fixes removing b7 smart scope not removing aiming traits.

- code/game/objects/items/reagent_containers/autoinjectors.dm
- code/game/objects/items/reagent_containers/glass.dm
- code/game/objects/items/reagent_containers/hypospray.dm
Автоинжекторы теперь могут вводить реагентов вплоть до 45.
Обычные гипоспреи до 120.
Улучшенные до 240.
Удобство.
```
:cl:
qol: Увеличен максимально возможно вводимый объем реагентов для гипоспреев.
/:cl:
```
> Increases possible transfer amounts for hyposprays.

- code/modules/vehicles/_hitbox.dm
При смене з-левела людей на танке больше не должно отправлять в свободное падение.
```
:cl:
fix: Исправлена отправка людей на танке в свободное падение при смене з-уровня.
/:cl:
```
> Tank space fix (#16492)

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
фиксит невозможность построить новые типы стен за хайвлорда
> фикс новых стен для хайвлорда

- code/modules/xenomorph/acidwell.dm
Если у колодца закончились заряды, то при уничтожении он не выпустит дыма.
Выглядит логичным что пустой колодец, не выпускает кислоту при уничтожении.
```
:cl:
fix: Кислотный колодец теперь не выпускает кислоту при уничтожении если его заряды меньше 1.
/:cl:
```
> Acid well now doesn't spread acid smoke on destruction if it's empty.

- _maps/map_files/Talos/TGS_Talos.dmm
- code/modules/power/cable.dm
Добавил отсутствующие, удалил лишние апц на Талосе.
Провода в ангаре теперь под касом. Провод именно под касом имеет флаг игнора шаттлов, поэтому ему норм.
> Adds missing apc's to Talos. Also changes hangar cables to be under CAS.

- code/_globalvars/lists/flavor_misc.dm
Предалиен теперь отображается в орбит меню.
Удобство
```
:cl:
qol: Предалиен теперь имеет иконку в орбит меню.
/:cl:
```
> Adds abomination icon to orbit menu.

- code/game/objects/items/motion_detector.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
```
RUNTIME: runtime error: Cannot read null.y
- proc name: prepare blip (/obj/item/armor_module/module/motion_detector/proc/prepare_blip)
-   source file: code/modules/clothing/modular_armor/attachments/modules.dm,872
-   usr: Alex \'Goida\' Brown (/mob/living/carbon/human)
-   src: Tactical sensor helmet module (/obj/item/armor_module/module/motion_detector)
-   usr.loc: the autodoc medical system (/obj/machinery/autodoc)
-   src.loc: the M10X pattern marine helmet (/obj/item/clothing/head/modular/m10x)
- Tactical sensor helmet module (/obj/item/armor_module/module/motion_detector): prepare blip(Viktor Ushkin (/mob/living/carbon/human), "friendly")
- Tactical sensor helmet module (/obj/item/armor_module/module/motion_detector): do scan()
- /datum/callback …
```
> Фикс рантайма детектора движения

- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/limbs.dm
```
[2024-09-07 09:52:21.938] RUNTIME: runtime error: Cannot read null.species
- proc name: droplimb (/datum/limb/proc/droplimb)
-   source file: code/modules/organs/limbs.dm,681
-   usr: null
-   src: r_hand (/datum/limb/hand/r_hand)
- r_hand (/datum/limb/hand/r_hand): droplimb(null, 0, 1)
- Jhon \'Frogy\' Richmand (/mob/living/carbon/human): gib()
- Jhon \'Frogy\' Richmand (/mob/living/carbon/human): ex act(250, null)
- /datum/automata_cell/explosion (/datum/automata_cell/explosion): update state(null)
- Cellular Automata (/datum/controller/subsystem/cellauto): fire(0)
- Cellular Automata (/datum/controller/subsystem/cellauto): ignite(0)
- Master (/datum/controller/master): RunQueue()
- Master (/datum/controller/master): Loop(2)
- Master (/datum/controller/master): …
```
> Фикс рантайма death() и droplimb()

- code/__HELPERS/game.dm
```
RUNTIME: runtime error: Cannot read null.images
- proc name: remove images from clients (/proc/remove_images_from_clients)
-   source file: code/__HELPERS/game.dm,94
-   usr: Mature Hunter (If) (/mob/living/carbon/xenomorph/hunter)
-   src: null
-   usr.loc: the cave (181,73,2) (/turf/open/floor/plating/ground/mars/random/cave)
- remove images from clients(, /list (/list))
- /datum/callback (/datum/callback): Invoke()
- world: PushUsr(Mature Hunter (If) (/mob/living/carbon/xenomorph/hunter), /datum/callback (/datum/callback))
- /datum/callback (/datum/callback): InvokeAsync()
- Timer (/datum/controller/subsystem/timer): fire(0)
- Timer (/datum/controller/subsystem/timer): ignite(0)
- Master (/datum/controller/master): RunQueue()
- Master (/datum/controller/master): …
```
> Фикс рантайма remove_images_from_clients

- code/game/objects/items/scanners.dm
Фикс рантайма при использовании медсканнера на робота.
```
RUNTIME: runtime error: Cannot read null.reagents
- proc name: ui static data (/obj/item/healthanalyzer/ui_static_data)
-   source file: code/game/objects/items/scanners.dm,197
-   usr: Pepa (/mob/living/carbon/human/species/synthetic)
-   src: the HF2 Medical Gloves (/obj/item/healthanalyzer/gloves)
-   usr.loc: the cave (136,72,2) (/turf/open/floor/plating/ground/mars/random/cave)
-   src.loc: Pepa (/mob/living/carbon/human/species/synthetic)
- the HF2 Medical Gloves (/obj/item/healthanalyzer/gloves): ui static data(Pepa (/mob/living/carbon/human/species/synthetic))
- /datum/tgui (/datum/tgui): get payload(null, 1, 1)
- /datum/tgui (/datum/tgui): open()
- the HF2 Medical Gloves (/obj/item/healthanalyzer/gloves): …
```
> Фикс рантайма медсканнера

- code/_onclick/item_attack.dm
```
RUNTIME: runtime error: Cannot read null.name
- proc name: ui static data (/obj/item/healthanalyzer/ui_static_data)
-   source file: code/game/objects/items/scanners.dm,163
-   usr: Diane \'Horny\' Belror (/mob/living/carbon/human)
-   src: the HF2 integrated health anal... (/obj/item/healthanalyzer/integrated)
-   usr.loc: the cave (153,68,2) (/turf/open/floor/plating/ground/mars/random/cave/rock)
-   src.loc: null
- the HF2 integrated health anal... (/obj/item/healthanalyzer/integrated): ui static data(Diane \'Horny\' Belror (/mob/living/carbon/human))
- /datum/tgui (/datum/tgui): get payload(null, 1, 1)
- /datum/tgui (/datum/tgui): send full update(null, null)
- /datum/callback (/datum/callback): Invoke()
- world: PushUsr(Diane \'Horny\' Belror …
```
> Фикс рантайма интегрированного медсканера

- _maps/shuttles/tgs_bigbury.dmm
- _maps/shuttles/tgs_canterbury.dmm
- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/last_stand.dm
При догрузке режимы краша и ласт стэнда обнуляют точки спавна сквадов.
Криокапсулы на Бигбери и Кантербери теперь смотрят в правильные стороны.
```
:cl:
fix: Летйджоин спавны на краше теперь должны работать.
/:cl:
```
> Fixes crash latejoin spawns and cryopod dirs on bigbury and canterbury.

- code/game/objects/machinery/doors/airlock.dm
- code/game/objects/shrapnel.dm
- code/modules/projectiles/projectile.dm
> Optimizes shrapnel code a bit.

- code/modules/reqs/clothing.dm
В карго добавлены сумка и рюкзак корпсманов, за 75 и 125 поинтов, рюкзак дороже так как в нём лучше батарея.
Теперь будет возможность приобрести рюкзак для дефиба, если проебал его.
```
:cl:
add: Добавил сумку и рюкзак корпсманов в карго.
/:cl:
```
> Adds corpsman satchel and backpack to cargo.

- code/modules/admin/admin_verbs.dm
Переименовал верб с `Jump` в `Jump To` чтобы при попытке использовать его в мобе, ты не прыгал.
```
:cl:
fix: Админский Jump теперь работает как нужно в живом теле.
/:cl:
```
> Fixes admin Jump verb.

- code/game/objects/items/weapons/blades.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/vehicles/armored/armored_weapons.dm
- code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Фикс
`[19:19:43] Runtime in code/__HELPERS/unsorted.dm, line 133: Cannot read null.x
proc name: get angle with scatter (/proc/get_angle_with_scatter)
usr: Ge4ok/(Denis Artillerist Gnatik)
usr.loc: (Tank Interior (109, 12, 4))
src: null
call stack:
get angle with scatter(the MT - Banteng (/obj/vehicle/sealed/armored/multitile), null, 0, 16, 16)
the secondary cupola minigun (/obj/item/armored_weapon/secondary_weapon): fire()
/datum/callback (/datum/callback): Invoke()
world: PushUsr(Denis Artillerist Gnatik (/mob/living/carbon/human), /datum/callback (/datum/callback))
/datum/callback (/datum/callback): Invoke()
/datum/component/automatedfire... (/datum/component/automatedfire/autofire): process shot()
Automated fire (/datum/controller/subsystem/automatedfire): fire(0)
Automated fire …
> Guns runtime fixes

- code/datums/components/attachment_handler.dm
Теперь не будет фантомной разгрузки при смене уже надетой на униформу.
```
:cl:
fix: Исправлены фантомные разгрузки при смене на надетой униформе.
/:cl:
```
> Fixes an attachment component bug (#15982)

- code/game/objects/machinery/kitchen/gibber.dm
Теперь нельзя запихнуть в гиббер из АПЦ человека если вы с ним одной фракции и его всё еще можно воскресить.
Ограничит индивидуумов от бана ввиду грифа.
```
:cl:
balance: В гиббер из АПЦ теперь нельзя пихать воскрешабельных товарищей.
/:cl:
```
> Adds undeffibable check for APC gibber.

- code/modules/mob/living/brain/brain.dm
- code/modules/organs/limb_objects.dm
> Fixes harddel of container and brainmob

- code/game/objects/items/explosives/grenades/grenade.dm
- code/game/objects/items/explosives/grenades/marines.dm
Теперь слип вызываться будет только если у гранаты есть звук, который оно будет проигрывать потом.
> Adds additional check for grenade throw_at.

- _maps/shuttles/minidropship_big.dmm
- _maps/shuttles/minidropship_factorio.dmm
- _maps/shuttles/minidropship_food.dmm
- _maps/shuttles/minidropship_mobile_bar.dmm
- _maps/shuttles/minidropship_standard.dmm
- _maps/shuttles/minidropship_umbilical.dmm
- code/game/objects/machinery/doors/poddoor.dm
- code/modules/power/apc/apc.dm
- code/modules/shuttle/on_move.dm
Тад теперь не ломает трубы, ибо я удалил код отвечающий за это. Ибо он говно.
Также вернул проверку перед проком обновления труб, ибо после отлёта все 450 труб обновляются, и вызывают пролаг.
Бункерные двери на таде теперь не смузятся со стенами и прочим говном.
Исправил харддел у апц.
```
:cl:
fix: ТАд не ломает трубы после отлёта
/:cl:
```
> Fixes tad breaking pipes for real this time.

- code/__DEFINES/loadout.dm
- code/modules/reqs/weapons.dm
Магазины на СГ153 теперь снова в карго.
```
:cl:
fix: Исправлено то что кастомных магазинов на СГ153 не было в карго.
/:cl:
```
> Fixes sg153 magazines missing from cargo.

- code/datums/jobs/job/job.dm
"Title. This just needs an early return, since this happens normally."
> Remove unneeded crash message (#14714)

- code/modules/mob/living/living_verbs.dm
Если моб на з-левеле Вальгаллы/Еорда то его не спрашивает "Уверены ли вы в том что хотите гостануться?"
Удобство.
```
:cl:
qol: Команда Ghost больше не требует подтверждения если использовать её на Вальгалле/Еорде.
/:cl:
```
> Ghost verb now doesn't need approval if mob is on centcomm z level.

- code/game/objects/items/scanners.dm
Если ты просканировал  ссд-шника, то в дальнейшем сканер будет отображать всех людей ССД.
```
:cl:
fix: Исправлено то что анализатор здоровья после сканирования ссд-шника, показывал всех как ссд.
/:cl:
```
> Fixes health analyzer SSD display (#14712)

- code/datums/gamemodes/_game_mode.dm
- code/datums/gamemodes/crash.dm
Таймер респавна ксеносов уменьшен с 5 до 3 минут.
Таймер респавна маринам до 15 урезали, а про ксен забыли.
```
:cl:
balance: Респавн ксеносов уменьшен с 5 минут до 3-ёх.
/:cl:
```
> Decreases xeno respawn time from 5 to 3 minutes.

- code/game/objects/obj_defense.dm
- code/game/objects/structures/barricade.dm
Теперь кады дают правильное кол-во материала при разборе.
```
:cl:
fix: Исправлено кол-во материала получаемого с разбора баррикад.
/:cl:
```
> Fixes barricade deconstruction.

- code/game/objects/explosion_recursive.dm
Должно пофиксить то что после броска вызванного взрывом, моб мог застрять в состоянии недоброска.
```
:cl:
fix: Исправил застревание после отбрасывания взрывом.
/:cl:
```
> Probably fixes getting stuck after explosion throws.

- code/modules/projectiles/guns/energy.dm
У самой винтовки кд на выстрел стоит в 0.4, у режима стрельбы стояло 0.5, снизил режиму до 0.4
```
:cl:
fix: Исправил то что скорострельность искрэй винтовки падала после смены режима стрельбы назад на стандартный.
/:cl:
```
> Fixes xray gun fire delay being inconsistent.

- code/modules/xenomorph/acidwell.dm
Кислотные колодцы теперь получают кислоту раз в 30 секунд вместо 5 секунд
> Acid well recharge rate

- code/game/objects/effects/effect_system/smoke.dm
- code/modules/xenomorph/acidwell.dm
Дым из кислотного колодца теперь прозрачный.
Исправлено то что при разрушении колодца, из него выходил не тот тип дыма.
Слишком легкая дымовая завеса, с учётом того что они сами по себе заполняются.
```
:cl:
balance: Дым из кислотных колодцев теперь прозрачный.
fix: При уничтожении кислотного колодца из него выходит правильный дым.
/:cl:
```
> Acid well smoke is now transparent.

- code/controllers/subsystem/minimaps.dm
- code/datums/interior/_interior.dm
- code/datums/interior/interior_tank.dm
Миникарты теперь работают в миникарте.
Фабрикатор танков теперь нельзя разрушить.
```
:cl:
fix: Миникарты теперь работают в танках.
fix: У фабрикатора для танков теперь есть защита от дебила.
/:cl:
```
> (Mostly) fixes tank minimaps (#15312) Also add idiot protection to tank fabricator.

- code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Исправил то что кража снимала плазму до того как завершилась успехом.
В 2 раза больше тильта из-за спизженных вещей.
```
:cl:
fix: Кража руни теперь не снимает плазму 2 раза.
```
> Fixes snatch spending 2x plasma.

- code/__DEFINES/mode.dm
- code/game/objects/items/cocoon.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
теперь за псидрейн всегда будет давать 90, а за кокон по 3 в минуту
> Удаление штрафов псипоинтов на хайпопе

- code/controllers/subsystem/silo.dm
исправлена формула в динамическом скейлинге
динамический скейлинг больше не считает миньонов
динамический скейлинг теперь работает не только в сторону маров, но и в сторону ксен (типо ксено бафф наверно)
> Silo scaling

- code/controllers/subsystem/minimaps.dm
- code/game/objects/machinery/mortar.dm
- tgui/packages/tgui/interfaces/Mortar.js
Добавляет кнопку для вывода координат на артиллерию с помощью миникарты. Миникарта открывается только если у тебя есть наушник с ней.
Также исправил то что при каждом юи акте, артиллерия воспроизводила сообщение о смене координат. Теперь только при их смене, как и должно быть.
Это и так можно делать если у тебя есть открытая в другой вкладке карта, так что почему бы не сделать это фичей.
```
:cl:
add: Добавил наводку по карте для артиллерии.
/:cl:
```
> Adds minimap targetting for artillery.

- code/__DEFINES/cooldowns.dm
- code/datums/components/deployable_item.dm
- code/modules/projectiles/mounted.dm
Теперь на поворот есть кд в 0.75 секунд.
Если поворот неправильный то тебе останавливает стрельбу, как и должно делать это логически.
Чутка поменял местами проверки в проке деплоя, чтобы сначала проверяло хочешь ли ты деплойнуть, и уже потом на то можешь ли ты деплойнуть.
Больше нельзя делать вот так:
https://github.com/user-attachments/assets/dfa12958-478c-4845-8bd8-c5ea37ade73a
Так выглядит сейчас:
https://github.com/user-attachments/assets/99dfce6b-04ce-4935-8220-d2a7ef3159da
```
:cl:
balance: Устанавливаемые орудия теперь нельзя вращать как карусель.
fix: Теперь тебе останавливает стрельбу из установленного оружия, если ты физически не можешь из него стрелять в выбранном направлении.
/:cl:
```
> Proper rotate restrictions for mounted weaponry.

- code/game/objects/machinery.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures.dm
- code/game/objects/structures/window.dm
- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
Кислотный дым теперь дамажит структуры и машинерию.
Удалил абилку смены глобы для не примо бойлера, так как она ничего у него не делает.
Уменьшил громкость звука при получении объекта бурн урона.
Бойлер бафф. Аое атака теперь будет дамажить окружение.
```
:cl:
add: Кислотный дым теперь дамажит структуры и машинерию.
/:cl:
```
> Acid smoke now damages structures and machinery.

- code/__DEFINES/equipment.dm
- code/datums/components/deployable_item.dm
- code/modules/projectiles/attachables/rail.dm
- code/modules/projectiles/guns/sentries.dm
Самодельные турели теперь нельзя ставить вплотную к другим турелям.
```
:cl:
fix: Самодельные турели теперь нельзя ставить вплотную к другим турелям.
/:cl:
```
> Sentry stacking restriction now works for buildasentry.

- code/modules/xenomorph/_xeno_structure.dm
Ксено структуры больше не получают урон от кислотного дыма.
```
:cl:
fix: Ксено структуры больше не получают урон от кислотного дыма.
/:cl:
```
> Fixes xeno structures getting damaged from acid smoke.

- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Нельзя стать невидимым за донат.
Никакого невидимого хантера за бабло.
```
:cl:
fix: Теперь нельзя стать невидимым за донат.
/:cl:
```
> Restricts toggle rouny from making xenos invisible, if there are no rouny versions.

- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Так как броски теперь в кои-то веки анбаклят тех кого бросило, керя выбрасывал жертв с неста.
```
:cl:
fix: Керя теперь не выбрасывает нестованных жертв с помощью Зова Лярвы.
/:cl:
```
> Fixes call of younger unbuckling nested victims.

- code/modules/xenomorph/_xeno_structure.dm
Фиксит вот это.
На игре никак не отобразится.
> `structure/xeno/Destroy()` now doesn't try to look for structure in critical structures if structure isn't critical.

- code/modules/reqs/_supply.dm
При покупке или переключении на другой транспорт, все орудия, модули и патроны сбрасываются, что предотвращает целую кучу возможного сломанного говна.
Нету танков с бесконечными патронами на основной ствол.
```
:cl:
fix: При покупке или переключении выбора транспорта в фабрикаторе транспорта, теперь сбрасывается выбор орудий, модулей и патрон, что исправляет танки с интерьером АПЦ и бесконечными патронами.
/:cl:
```
> Fixes most of vehicle fabricator bullshit.

- code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Постройка колодцев с кислотой теперь занимает 0.5 секунд по времени.
Мне не нравится то что защитная структура, может быть так легко использована в атаке.
```
:cl:
balance: Постройка колодцев с кислотой теперь занимает 0.5 секунды.
/:cl:
```
> Adds 0.5 second do_after for building acid wells.

- code/modules/clothing/under/marine_uniform.dm
Исправил то что у /obj/item/clothing/under/marine/service были опции для смены спрайта на несуществующие версии.
```
:cl:
fix: TGMC service uniform теперь не имеет функции становиться невидимым спрайтом.
/:cl:
```
> Fixes service uniform being invisible on rolling sleeves.

- _maps/map_files/Talos/TGS_Talos.dmm
Заменил рипли в карго на рипли дроид для ИИ.
ИИ теперь может быть грузчиком на пол ставки.
```
:cl:
map: На Талос добавлен карго дроид для ИИ.
/:cl:
```
> Adds cargo droid for Talos.

- _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
- code/game/area/barrenquilla_mining.dm
Одно сило перенёс в уже существующую уборную, вокруг второго сило построил мини руины.
Также исправил то что в одном комплексе комната со стиралками заимствовала зону из призона.
Лярвы не будут умирать при спавне.
```
:cl:
map: [Барренквилла] Северные сило на краше теперь не подвержены песчаной буре.
/:cl:
```
> Few barrenquilla fixes.

- _maps/map_files/Talos/TGS_Talos.dmm
Исправил доступ на двери в комнатах пилотов, чтобы её мог открыть пилот.
```
:cl:
map: [Талос] Исправлена дверь в комнате пилота, не открывающаяся доступом пилота.
/:cl:
```
> Fixes pilotbunks door access so it can be opened by a pilot.

- code/modules/clothing/modular_armor/attachments/modules.dm
Убрал -армор у модуля тюр и мимир
Малоиграбельные модули, которые не юзаются из-за очевидного дебаффа в защите. Решение - убрать дебафф.
Ну а еще - маринбаф
```
:cl:
balance: мимир1 и мимир2 больше не уменьшают melee армор
balance: тюр1 и тюр2 больше не уменьшают acid и bio армор
/:cl:
```
> tyr and mimir buff

- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Рандом урона 15-30 от ацидблада понижен до 5-15
Механика ацидблада не убивает в 100% случаях зажима в мили зоне. Однако, все еще остается наносящей урон.
```
:cl:
balance: ацидблад наносит 5-15 урона кислотой заместо 15-30
/:cl:
```
> nerf acidblood 15-30 >> 5-15

- code/_onclick/hud/screen_objects/menu_text_objects.dm
- code/datums/datacore.dm
Можно решить хочешь ли ты играть за ксеносов прямо из лобби.
```
:cl:
qol: Ксено манифест теперь отображает всех ксеносов в хайве.
/:cl:
```
> Makes xeno manifest actually useful. Unifies Marine Manifest and Xeno manifest in 1 lobby button.

- code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
- code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Убрал дублирующийся звук у примо и мелкие рантаймы.
Баг фикс.
Убрал дублирование звука у примо и мелкие рантаймы.
```
:cl:
fix: Исправил дублирование звука у примо крашера.
fix: Исправил два рантайма, которые появлялись после каждого использования абилки.
/:cl:
```
> Crusher bugfix

- code/datums/components/_component.dm
- code/datums/greyscale/_greyscale_config.dm
- code/modules/admin/panels/permission_panel.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/datumvars.dm
- code/modules/mob/mob.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/power/power.dm
- code/modules/security_levels/keycard_authentication.dm
- tools/ci/od_lints.dm
Поправил ноющие линтеры.
На игроках не отобразится.
> Fixes linters whining.

- code/game/objects/machinery/mortar.dm
- code/modules/projectiles/ammo_datums/artillery.dm
- code/modules/reqs/explosives.dm
Дал богам войны больше веселья
Ховайзер:
Теперь ховайзер может делать больно только при умелом использовании вебмапы или при хорошем наводчике, но делает намного больнее чем раньше
МЛРС теперь лучше накрывает площади, снаряды подешевле, Х-50 теперь еще и зажигательные помимо газа, добавлены тенгл снаряды с ЛХЕ функцией
А миномет, вроде, итак со своей задачей хорошо справляется
Будет веселее
> Миномет: около-унивенсальное оружие. Имеет меньшее покрытие газами и огнем, чем РСЗО, и меньший урон, чем гаубица, но может выполнять оба функционала.
Гаубица: высокий урон от бабахов
РСЗО: покрытие большой площади зажигательными снарядами, тгазом, дымами, светом
https://discord.com/channels/1235677154084126861/1244698886753222818/1288370849698680882
```
:cl:
add: Тенглфут снаряды для РСЗО в карго. …
```
> Баффы арты

- code/__DEFINES/objects.dm
- code/game/objects/structures/dropship_equipment.dm
Орудия для каса больше нельзя прикрепить к другим шаттлам.
```
:cl:
fix: Орудия для каса больше нельзя прикрепить к другим шаттлам.
/:cl:
```
> Cas weaponry doesn't fit on other shuttles now.

- code/__DEFINES/loadout.dm
- code/game/objects/items/loot_box.dm
- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/codex/entries/magazine_codex.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/rifles.dm
- code/modules/reqs/weapons.dm
Удалил ХЕ патроны на tx54.
Данный тип снарядов не удался концептуально. На данный момент эти патроны стоят дороже чем обычные, но уступают им чуть ли не во всём, но если им повысить силу взрыва, то это будут уже ИФФ ракеты из-за экрана. В обоих случаях будет говном, просто для разных сторон.
```
:cl:
del: Удалил ХЕ патроны на tx54.
/:cl:
```
> Deletes tx54 he ammo.

- code/__DEFINES/jobs.dm
Снизил с 1 до 0.5 генерацию лярвапоинтов для небоевых ролей шипсайда(кроме синта, пилотов)
Шипсайд не сражается на земле > меньше влияния шипсайда на количество беносов на планете
```
:cl:
balance: Генерация лярвапоинтов с небоевых шипсайд ролей снижена с 1 до 0.5
/:cl:
```
> Change larvapoints from shipside roles

- code/game/objects/machinery/OpTable.dm
- code/game/objects/machinery/bioprinter.dm
Светящиеся элементы биопринтера и операционного стола теперь видно в темноте.
```
:cl:
fix: Светящиеся элементы биопринтера и операционного стола теперь видно в темноте.
/:cl:
```
> Proper lights for optable and bioprinter, so their emissives are seen.

- code/modules/mob/living/carbon/xenomorph/evolution.dm
Фиксит вот это:
```
:cl:
fix: Теперь нельзя эволюционировать обходя лимит тиров с помощью регресса/каст свапа.
/:cl:
```
> You can't evolve into limited next tiers, with caste swap\regress.

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/projectiles/guns/flamer.dm
Вернул спрей насадку
Обычная насадка прожигает до 3 стен
Спрей насадка прожигает до 7 стен
Фидбек + бафф очевидно слабых огнеметов
```
:cl:
balance: Спрей-насадка возвращена в вендор оружия
balance: Спрей насадка прожигает до 7 стенок вместо 9
balance: Обычная насадка прожигает до 3 стенок вместо 2
/:cl:
```
> Change wall flame pen and add wide spray

- code/game/turfs/walls/resin.dm
Нерф специализированных ксеностенок, переигровка статов стандартной стенки
Очевидно, что теперь милипруф стенки не будут иметь по 70 софтармора от буллета и лазера, как и другие специализированные стенки.
```
:cl:
balance: Обычная ксеностенка: софтармор мили 30
balance: Бомбпруф: софтармор 15 мили, 35 буллет, 30 лазер вместо 70 буллет и 60 лазера
balance: Фаерпруф: софтармор 15 мили, 35 буллет, 30 лазер вместо 70 буллет и 60 лазера
balance: Милипруф: софтармор 35 буллет, 30 лазер вместо 70 буллет и 60 лазера
balance: Буллетпруф: софтармор 15 мили вместо 0
/:cl:
```
> Нерф ксеностенок

- code/game/objects/explosion_recursive.dm
`var/range = min(round(severity * 0.2, 1), 14)` было сделано так что ранж меньше 14, у тебя был только если взрыв был слабее 70, когда в тех же м40 гранатах сила взрыва 115.
Изменено на `var/range = min(round(severity * 0.07, 1), 14)`
Скорость была в виде `var/speed = max(range * 2.5, 4)`, что с учётом вечного ренжа в 14, множила её в 2.5 раза, из чего получалось что урон от броска множился на 35, потом делился на 5, и получалось что с броска копья с уроном в 45 урона, тебе прилетало 315 урона. Что сразу отрубает конечности, голову и делает перелом с ИБ. И ничто не мешает это дело стакать для лучшего эффекта.
Изменено на `var/speed = max(range, 3)`
Взрывные ловушки станут чуть адекватнее.
```
:cl:
balance: Понёрфил силу отбрасывания от взрывов.
/:cl:
```
> Nerfs explosion throw.

- code/modules/projectiles/projectile.dm
Теперь проверка идёт не только на то существует ли `damage`, а и на то выше ли он 0.
Баф хода.
Что-то вроде этого:
https://www.youtube.com/watch?v=ebWgte2395M
```
:cl:
fix: Теперь нельзя получить шрапнель, если урон пули был ниже 1.
/:cl:
```
> Bullet feedback now properly checks for bullet damage.

- code/modules/projectiles/guns/grenade_launchers.dm
Подствольный гранатомет вмещает 2 гранаты и теперь может использовать все доступные в игре гранаты
Повышение играбельности модуля, фидбек игроков
```
:cl:
balance: Подствольный гранатомет вмещает 2 гранаты.
balance: Подствольный гранатомет теперь вмещает в себя м15 и трейлблейзеры.
/:cl:
```
> Бафф подствольного гранатомета

- _maps/map_files/Talos/TGS_Talos.dmm
- tools/UpdatePaths/scripts/telecomms.txt
На Талосе теперь правильный ресивер телекомов, позволяющий общаться на общем канале связи.
```
:cl:
map: На Талосе теперь правильный ресивер телекомов, позволяющий общаться на общем канале связи.
/:cl:
```
> Fixes wrong receiver type on Talos telecomms.

- code/game/objects/items/flashlight.dm
Исправил то что включенные лампы, в саду Талоса, выглядели как выключенные.
```
:cl:
fix: Исправил то что включенные лампы, в саду Талоса, выглядели как выключенные.
/:cl:
```
> Fixes turned on lanterns, having turned off sprite.

- code/game/objects/machinery/vending/vending.dm
Исправлено то что подключенные к оружию магазину, не сбрасывали подключение к оружию при возврате в вендор.
```
:cl:
fix: Исправлено то что подключенные к оружию магазину, не сбрасывали подключение к оружию при возврате в вендор.
/:cl:
```
> Fixes connected ammo magazines not unloading from the gun on vendor restock.

- code/datums/elements/riding.dm
- code/game/objects/items/weapons/twohanded.dm
- code/modules/mob/inventory.dm
Offhand-ы теперь не перекрывают предметы.
Наверное лучше видимость?
```
:cl:
add: Offhand-ы теперь визуально ниже взятых предметов.
/:cl:
```
> Offhand layer is lower than item layer.

- code/__DEFINES/jobs.dm
- code/datums/jobs/job/job.dm
- code/datums/jobs/job/marines.dm
СЛ-а теперь можно открыть играя и за маринов, и за командующий состав.
В теории при игре за СЛ-а, также будет начислять время и на командование, и на маринов, что поможет открыть того же ФК.
Недочёт.
```
:cl:
add: СЛ-а теперь можно открыть играя и за маринов, и за командующий состав.
/:cl:
```
> Squad Leader now needs either marine exp, or command exp to play.

- code/game/objects/items/jetpack.dm
Бафф и так редкоиспользуемого джетпака
Джетпак можно применять находясь в стаггере. Честно похоже на баг
Теперь марин может использовать джетпак несмотря на боль. Нелогично что мар спокойно стоя на ногах не мог его использовать и избегать особо критичных ситуаций для которых джетпак и был создан.
```
:cl:
balance: Джетпаку убрана проверка на стаггер
/:cl:
```
> jetpackWithoutStagger

- code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Изменил статы ХП и/или армора у большей части каст.
Более явное разделение на беносов, против которых вариативно использование ХП/АП патронов.
Повышение выживаемости и/или играбельности танков.
Повышение играбельности лазерок.
```
:cl:
balance: Бегемот получил 12 харда от буллета, потерял хард от мили, снижен хард от лазеров с 12 до 6
balance: Крашеру поднято ХП с 400 до 500, понерфлен софтармор от мили с 80 до 50, лазеры с 80 до 65
balance: Дефендеру поднято ХП с 320 до 410, получил хардармор 10 от буллета
balance: Претору поднято ХП с 460 до 570, снижен софтармор буллета с 50 до 25, лазеров с 50 до 15
balance: Сентинелю поднято ХП с 300 до 400
balance: Спиттеру поднято ХП с 310 до 450, софтармор буллета снижен с 35 до 20, лазеров с 35 до 10
/:cl:
```
> Rebalance xeno HP and armor

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Между дверьми теперь должно быть минимум 2 тайла для их постройки
Не будет раковых застроек всего дверьми, отвратительных по многим причинам.
```
:cl:
balance: Теперь между ксенодверьми должно быть минимум 2 тайла для их постройки.
/:cl:
```
> Ксенодверям надо 2 тайла между собой для постройки

- code/__DEFINES/loadout.dm
- code/game/objects/machinery/vending/marine_vending.dm
1. Перевел оружейные разделы
2. Вернул лазганы в общий вендор
3. Перетащил сентри в специалист-раздел, стационарные пулеметы в раздел пулеметов
4. Вернул т18
Немного отсортированные разделы, небольшая работа по переводу, возвращение лазганов во все ручки
```
:cl:
balance: Лагзаны возвращены в оружейный вендор
balance: AR-18 возвращена в оружейный вендор
balance: Паверфикст возвращен в оружейный вендор
spellcheck: Перевод разделов оружейного вендора
code: Турели перенесены в раздел Специалистам, стационарные пулеметы в раздел пулеметов
/:cl:
```
> Перевод разделов, возвращение лазерганов, перенос ряда пушек в разделы

- code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
Хаггер оверлей на Керриере теперь опять работает.
```
:cl:
fix: Хаггер оверлей на Керриере теперь опять работает.
/:cl:
```
> Fixes carrier hugger overlays not applying correctly.

- code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Спиттеру добавлена липкая кислотная граната в примо, идея честно спизжена с оффов. Работает как трейлблейзер только с кислотой. Не слишком сильно, фрилансеру наносит +- 50 урона.
У примо спиттера теперь сильная кислота, вместо обычной.
Примо спиттера теперь станет чуточку полезнее.
```
:cl:
add: Спиттеру добавлена липкая кислотная граната в примо. Работает как трейлблейзер только с кислотой.
balance: У примо спиттера теперь сильная кислота, вместо обычной.
/:cl:
```
> Adds sticky acid grenade for primordial spitter. Also now has strong acid.

- code/game/objects/machinery/vending/marine_vending.dm
Фикс
Фикс
```
:cl:
fix: Паверфист теперь есть в оружейном вендоре на дистрессе
/:cl:
```
> Фикс отсутствия паверфиста на дистрессе

- code/modules/reqs/engineering.dm
- code/modules/reqs/supplies.dm
Добавляет ручной зарядник для батареек за 80 пойнтов, и ящик с МРЕ за 65 пойнтов в карго.
Инженерный ручной зарядник давно напрашивался, учитывая, что весь медицинский стафф включая улучшенные дефибы и т.д. можно купить в карго. Коробка с МРЕ даст возможность марам с радиопаком раскошелится на личные пойнты, чтобы покушать, ну и отряд покормить. Идеально для антисоциальных морпехов, или в случае отсутствия шипсайда в карго.
```
:cl:
add: Добавил handheld charger в инженерный раздел карго за 85 пойнтов.
add: Добавил Emergency Provision Crate (EPC) с 10 МРЕ внутри в раздел снабжения карго за 65 пойнтов.
/:cl:
```
> Handheld Charger and MRE for Cargo.

- code/game/objects/effects/decals/decal.dm
- code/game/objects/effects/decals/turfdecals/markings.dm
- code/game/objects/effects/effect.dm
- code/game/objects/explosion_recursive.dm
- code/game/objects/items/reagent_containers/syringes.dm
- code/game/objects/structures/supplypod.dm
Заменил `spawn()` в коде взрывов на `addtimer` и `INVOKE_ASYNC`
Также взрывы теперь ломают всю краску на полу, а не только определенную.
На локалке чуть-чуть ускорило взрывы.
Также должно помочь с тем что удаление взрывов занимало много времени.
```
:cl:
code: Заменил `spawn()` в коде взрывов на `addtimer` и `INVOKE_ASYNC`
/:cl:
```
> Replaces `spawn()` in explosion code to `addtimer` and `INVOKE_ASYNC`.

- code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
Во время действия своих токсик ударов, (где-то 4.5 секунды) сент получает +60 буллет армора.
Сент сможет во время основной фазы боя (когда даёт свой прокаст) не умерать за один зажим. Возможно на нём снова можно будет играть
ИДЕЯ НЕ МОЯ, ВСЕ ДОЁБЫ К МЫКОЛЕ
```
:cl:
add: Сентинель теперь получает +60 буллет армора на время активации своих токсичных ударов.
/:cl:
```
> T1 Crusher (Sent)

- code/datums/gamemodes/_game_mode.dm
- code/modules/shuttle/marine_dropship.dm
Изменил формулу для хайджака с `Если маринов > 5` на `Если маринов > чем ксеносов`
В теории при подсчёте ксеносов не должны учитываться миньоны и хм, так что не должно получиться ранних хайджаков из-за кучи спавнеров.
Хайджак станет немного справедливее к ксеносам?
```
:cl:
balance: Изменил формулу для хайджака с `Если маринов > 5` на `Если маринов > чем ксеносов`
/:cl:
```
> Сhanges the amount of marines required to block hijack.

- code/game/objects/items/explosives/grenades/marines.dm
Флаера теперь не горят о полчаса, а от 1.5 до 2 минут
Теперь сложней засрать карту флаерами, которые горят половину раунда
```
:cl:
balance: Флаера теперь горят от 1.5 до 2 минут вместо 25-30 минут
/:cl:
```
> Нерф флаеров

- code/modules/admin/admin_verbs.dm
Исправил то что "Jump To Area" не работал.
```
:cl:
fix: Исправил то что "Jump To Area" не работал.
/:cl:
```
> Fixes jump to area verb.

- code/datums/keybinding/living.dm
Изменил дефолтный кейбинд для прыжка с пробела на V, так как они конфликтуют.
Давно пора
```
:cl:
qol: Изменил дефолтный кейбинд для прыжка с пробела на V.
/:cl:
```
> Changes default jumping keybind from Space to V.

- interface/interface.dm
- interface/skin.dmf
- tgui/packages/tgui-panel/themes.ts
Перевел запросы от кнопок в тгуи.
Чуть сместил чтобы последняя кнопка не пропадала за экраном, и не было много свободного пространства.
Исправил то что у кнопки для бусти не было своей темы, из-за чего она всегда была белой.
Чуть красивее.
```
:cl:
fix: Интерфейс кнопка для бусты теперь не выбивается из общей темы остальных кнопок.
/:cl:
```
> Fixes boosty button theme. Some adjucements to interface buttons.

- code/modules/projectiles/ammo_datums/bullet/machinegun.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/rifles.dm
Сг29 теперь использует один патрон с Сг25, различий там только в цифрах пробития и точной дистанции стрельбы.
Точная дистанция стрельбы сг29 поднята с 8 до 20. Пробитие поднято с 25 до 45. Задержка между выстрелами уменьшена с 0.2 секунд до 0.15.
В стерильных условиях от сг29 варриор умирает за 4.5 секунд, от сг25 умирает за 6 секунд.
Сг29 станет альтернативой сг25, а не просто неиспользуемой пушкой.
```
:cl:
balance: Точная дистанция стрельбы сг29 поднята с 8 до 20. Пробитие поднято с 25 до 45. Задержка между выстрелами уменьшена с 0.2 секунд до 0.15.
/:cl:
```
> Buffs sg29.

- _maps/map_files/Talos/TGS_Talos.dmm
- code/modules/security_levels/keycard_authentication.dm
Расставил кейкард аутентификаторы по комнатах коммандования.
Следующий этап игры для маринов не будет блокироваться из-за одного упущенного ксеноса на шипе.
```
:cl:
map: Кейкард аутентификаторы теперь есть не только на мостике, но и в комнатах коммандования.
/:cl:
```
> Adds keycard authenticators to command rooms.

- code/modules/projectiles/ammo_datums/bullet/machinegun.dm
- code/modules/projectiles/magazines/specialist.dm
Вернул статы СГ-85 до его баффа (нерфа) Татаром, добавил шаттер на 3 секунды.
Вилка для стен станет миниганом, способным любой касте нанести урон, как и полагается СГ, и снизить защиту для челиков с ХП патронами (такие существуют?). Брать слот СГшера ради сноса стен и убийства 6 ксеносов из каст Т1-Т2, когда абсолютно любой негр ходит под ферами защиты кинга/квины + апгрейдами и минусовым 20 АП у пушки - вышка парада кринжа. Для этих целей есть ХП патроны у бесплатных пукалок.
Да - с этой пушкой ты не пойдёшь беззаботно рашить застрой в сравнении с Т25 (абалдеть, а чё другой геймплей существует?), но, стреляя из-за спин союзников, заливая всё пространство пулями и прикрывая тыл, можно принести не меньший импакт, тем более со снижением брони на 20% на 3 секунды с выстрела.
```
:cl: …
```
> SG-85 goes BRRR

- code/_onclick/hud/screen_objects/menu_text_objects.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Удалил затемнение при эволюции ксеносов.
Исправил то что оповещение о появлении правителя хайва неправильно отображало его имя.
Добавил проверку на нулл в `add_xeno()`, возможно это поможет с поломкой хайвстатуса.
Затемнение экрана после эволюции - лишь плацебо, и пользы от него немного.
```
:cl:
del: Удалил затемнение при эволюции ксеносов.
fix: Исправил то что оповещение о появлении правителя хайва неправильно отображало его имя.
/:cl:
```
> Removes evolution fade in. Xeno ruler announcement is now correct. Some experimental tweaks.

- code/game/objects/machinery/vending/marine_vending.dm
Удалил бесплатные карго боеприпасы из карго вендора во вкладке "Surplus Special Equipment" (шахидок)
Непонятно зачем и почему, в карго вендоре вот просто есть халявные боеприпасы.
```
:cl:
del: Удалил бесплатные карго боеприпасы из карго вендора во вкладке "Surplus Special Equipment" (шахидок)
/:cl:
```
> Deletes free cargo ammunition from cargo vendor's "Surplus Special Equipment" tab

- code/modules/clothing/modular_armor/attachments/modules.dm
- code/modules/reqs/armor.dm
- code/modules/xenomorph/acidwell.dm
Увеличил защиту от кислоты у обеих версий мимимирки, у МК1 урезал защиту от газов, уменьшил урон от попадания в колодцы при частичном/полном комплекте мимира и шлема, поднял цену МК2 в карго до 160 поинтов.
Морпехи в МК2 и МК1 будут отлетать от плевков дольше (в МК2 в почти два раза дольше). Теперь урон (вернее АП) колодцев дополнительно режется в зависимости от надетого шлема + версии мимира. МК2 позволяет ходить в кислотных облаках и прочих дымах без стыда и совести (возможно надо нерфить), МК1 же справляется в два раза хуже и будет пропускать урон от кислотных облаков и пропускать в тело газы (до этого у МК1 был такой же полный игнор всех газов как у МК2).
Цена была поднята исходя из простой логики: тюр даёт небольшое повышение выживаемости (+5/+10) против самого частого урона, мимир …
> Mimir great again V2

- code/datums/components/deployable_item.dm
Фиксит возможность установить/снять любую раскладываемую вещь под действием камня ("Petrify") Кинга.
Ну, хуй знает, наверное багфиксы - это хорошо?
```
:cl:
fix: Больше в камне Кинга нельзя установить/снять любую раскладываемую вещь.
/:cl:
```
> Fix King ability "Petrify"

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Исправил то что таймер смерти Т4 ксеносов не работал.
```
:cl:
fix: Исправил то что таймер смерти Т4 ксеносов не работал.
/:cl:
```
> Xeno leader death timer fix (#15868)

- code/modules/language/language_holder.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Хайвмайнд теперь понимает язык маров
Прикольно. Синт может базарить на языке ксенов, почему ХМу хотя бы не понимать язык маров?
```
:cl: MrFloppa
add: Хайвмайнд теперь понимает язык маров
/:cl:
```
Я к*деренок маленький, возможно там будут баги какие-то хз, ошибок при компиле/рантаймов не словил
> Хайвмайнд понимает маров

- code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Создать спайдерлинга больше нельзя если у абилки нет зарядов
```
:cl:
fix: Создать спайдерлинга больше нельзя если у абилки нет зарядов
/:cl:
```
> widow bugfix

- code/datums/elements/shrapnel_removal.dm
Время фамбла перед вытаскиванием шрапнели уменьшено вдвое, за счёт переделки формулы.
Эта формула была говном по 2-ум причинам:
1. Вместо логичного сокращения времени фамбла для людей обладающих мед. навыком выше полного нуля (СЛ-ы), оно просто умножало время для всех у кого навык медицины был ниже СЛ-ского.
2. Она нигде не задокументирована, узнать о ней можно только найдя в самом коде. Все изменения вытаскивания шрапнели были сделаны без её учёта.
Из-за этого при задуманном времени фамбла в 12 секунд, обычные мары получали 24 секунд ожидания, помимо 30 урона на конечности, что может привести к легкому перелому.
```
:cl:
balance: Время фамбла перед вытаскиванием шрапнели уменьшено вдвое, за счёт переделки формулы.
/:cl:
```
> Decreseases fumbling time for shrapnel removal in 2 times.

- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Вампиризм охотнику, после набивания пяти стаков крипплинг страйк начинает восстанавливать по 12 ХП за удар
У хантера мало ХП и брони, такая низкая выживаемость должна компенсироваться абилкой, которая эту выживаемость будет повышать. В данном случае - вампиризм.
```
:cl:
balance: Добавил Хантеру вампиризм.
/:cl:
```
> Gives hunter vampirism

- code/modules/reqtorio/assembly_crafts.dm
- code/modules/vehicles/armored/ammo_magazine.dm
Завод который может производить как садары так и поды может производить снаряды повышенного калибра
Цены:
ХЕ танковый снаряд - 1 ювелирная сталь, 5 пороха
Бронебойный танковый снаряд - 2 ювелирных стали, 3 пороха
TOW танковый магазин - 3 ювелирных стали, 6 пороха
ХЕ снаряд ФК88 -  25 ювелирной стали, 30 пороха
Бронебойный снаряд ФК88 - 30 ювелирной стали, 25 пороха
```
:cl:
balance: Завод может производить снаряды для ФК88 и главного орудия танка
fix: Описание TOW магазина для главного орудия танка исправлено
/:cl:
```
> Завод теперь может производить снаряды для ФК88 и танковые снаряды для главного орудия

- code/modules/organs/organs.dm
Кап реагентов без бедтрипа стал 10 вместо 8
можно чуть больше запихнуть в себя химии имея модуль специально созданный чтобы предотвращать побочный эффект, ввиде Confuse, от ее количества
```
:cl:
balance: Кап реагентов с модулем Freyr изменен с 8 до 10
/:cl:
```
> Повышение капа реагентов с фреером до 10 вместо 8

- code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
- code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
Немного уменьшил кд и плазмакост абилкам, добавил небольшой вампиризм.
На Пантеру теперь не работают френзи феры.
Бафф относительно слабой касты.
```
:cl:
balance: На Пантеру и Раннера теперь не работают френзи феры.
balance: Уменьшил урон с 23 до 21
balance: Pounce КД теперь 8 секунд, плазмакост теперь 15(было 20). При паунсе на мара хилит немного ХП.
balance: Tearing Tail КД теперь 10 секунд, плазмакост уменьшен с 50 до 35. Хил увеличен с 25 до 35.
balance: Adrenaline Jump КД уменьшен с 12 до 8 секунд, плазмакост 15 -> 10.
/:cl:
```
> Panther buff

- code/datums/view.dm
- code/game/verbs/ooc.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
Портанул этот [ПР](https://github.com/tgstation/tgstation/pull/65225), чуток улучшает код авто фита вьюпорта
```
:cl:
refactor: Переделал код у Fit Viewport
/:cl:
```
> Port fix auto Fit Viewport

- code/modules/projectiles/ammo_datums/bullet/submachinegun.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/guns/smgs.dm
1. Фаллоу вектора теперь 1.75
2. Убрал дубли allowed_ammo_types
Пушка играбельная, в коде меньше насрано говна
```
:cl:
balance: Фаллоу вектора 3 >> 1.75
code: Убраны дубликаты allowed_ammo_types у АРкок
/:cl:
```
> Фаллов Вектор 3 >> 1.75, убрал дубликаты кода allowed_ammo_types

- code/game/objects/structures/stool_bed_chair_nest/bed.dm
- code/modules/vehicles/armored/interiors/chairs.dm
Можно было скрутить кресло водителя танка/бтра, из-за чего танк становился бесполезным, добавил иф что бы не убиваемое кресло было также и не скручиваемым
ноу фанни
```
:cl:
fix: Танковое кресло не возможно скрутить
/:cl:
```
> Fix tank chair wrench

- code/game/objects/items/scanners.dm
У реагент сканера все еще не было иконки.
[issue dis](https://discord.com/channels/1235677154084126861/1293833484795641928)
Использование реагент сканера станет реальным
```
:cl:
fix: Вернул иконку реагент сканеру
/:cl:
```
> Reagent scanner icon fix

- code/game/objects/items/storage/storage.dm
Раньше на альт клик брал самый левый предмет из инвентаря, сейчас это не так. Некоторым это может сильно пригодится. Теперь можно взять самый левый предмет через ctrl+shift+click. Этот багфикс https://discord.com/channels/1235677154084126861/1303481217626144800
```
:cl:
fix: Теперь ctrl+shift+click позволят взять самый левый предмет.
/:cl:
```
> Old alt+rightclick (take left object from storage)

- code/modules/projectiles/magazines/specialist.dm
Ракеты от РЛки теперь нормального размера, а не булочка
Теперь они смогут влезать в эксплозив пауч, в который они и ДОЛЖНЫ влезать. Ракеты от садара имеют нормальный размер, по логике и эти ракеты должны иметь нормальный размер. _ксенок*деры чертовы, если скажите что это баланс и заставите переделывать, то Аллах вас не простит!!!_
```
:cl: MrFloppa
balance: Ракеты для RL-160 теперь normal-sized, вместо bulky
/:cl:
```
> Changes RL-160 rocket size.

- code/game/objects/items/storage/storage.dm
Рюкзаки не закрываются если предмет слишком большой. 
Люди жаловались что когда воюешь, открываешь патч и хочешь убрать оружие, оружие закидывалось в бэк бэк по ошибке, и это его закрывало, что было очень не удобно, также если положить в переполненое хранилище предмет оно тоже закрывается что ОЧЕНЬ не удобно.
[Discod issue](https://discord.com/channels/1235677154084126861/1304840767788814366)
```
:cl:
fix: Теперь если положить слишком большей предмет в хранилище оно не закроется.
/:cl:
```
> Storage close fix

- code/__DEFINES/preferences.dm
- code/_onclick/hud/parallax.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/shuttle/on_move.dm
Портировал основное для работы чуть фикшеного параллакса
Портировал [ПР который улучшает красоту параллакса](https://github.com/tgstation/tgstation/pull/83395) и чуток [этого ПРа](https://github.com/tgstation/tgstation/pull/66567)
Меньше лагов и нагрузки, даже у себя на локалке (вроде) почувствовал эффект
```
:cl:
fix: Параллакс меньше нагружает систему
/:cl:
```
> Port parallax

- code/modules/projectiles/attachables/rail.dm
- code/modules/projectiles/attachables/scope.dm
- code/modules/projectiles/guns/rifles.dm
ченджлог
модуль превращающий пушку в смартган? нет спасибо
```
:cl:
del: б7 не даёт ифф, а даёт аим мод
del: скоупы не дают аим мод
del: у мг 60 удалён аим мода
/:cl:
```
> Removes iff from b7 scope, removes aim mode from scopes.

- code/modules/reqs/supplypacks/vehicles.dm
- code/modules/reqtorio/assembly_crafts.dm
Добавил для granade launcher боезапас в карго и в завод.
Фикс цены на заряды для ФК и танка, так как они стоили 2 раза больше чем в карго, если не больше, например 1 фк заряд стоил БОЛЬШЕ 250 ОЧКОВ, когда в карго он покупался за 100. Также с танковыми снарядами, в карго 10 в заводе 20+
Завод может стать более полезным по факту.
```
:cl:
add: Добавил Grenade launcher magazine в завод и карго
balance: Изменил цену боезапаса танка в заводе
balance: Изменил цену боезапаса фк в заводе
/:cl:
```
> Change FK88 ammo cost in factory and add granade launcher ammo

- code/modules/codex/entries/guns_codex.dm
При осмотре в кодексе больше информации, в более понятном формате.
Инфа про урон не работает на лаз оружие (это не огнестрел лол).
Астрологи объявили неделю QoL. Количество необходимых вики-страниц сократилось вдвое.
```
:cl:
qol: Кодекс (осмотр) оружия показывает больше информации
/:cl:
```
> Кодекс огнестрела 2.0

- code/__DEFINES/xeno.dm
- code/datums/status_effects/xeno_buffs.dm
- code/game/objects/structures/xeno/resin.dm
Нерф некоторых апгрейдов. Липкая резина теперь исчезает со временем. Нейротоксин заменен на сангвинал.
БАЛАНС
```
:cl:
add: Липкая резина исчезает со временем.
add: Нейротоксин заменен на сангвинал
balance: Армор теперь увеличивается только на 2.5 за чамбер вместо 5.
balance: Реген за чамбер 0.05 -> 0.008. Сандер 0.33 -> 0.166
balance: Вампиризм за чамбер 0.033 -> 0.016
balance: Сила фер за чамбер 1 -> 0.5
/:cl:
```
> Xeno upgrades nerf

- code/game/objects/machinery/vending/vending_types.dm
Имиалки теперь не только спаунится в медпоясах, но и в наномед плюсе в количестве шести банок
Не нужно брать пояса со склада или сливать инъекторы в бикер, банку со смесью можно взять в вендоре. Продолжение логики с сахаром и комбатмиксом, отчасти с сино и прочим, когда морпехам нет необходимости ничего делать в химии, всё необходимое сварено/намешено за них и так, что в общем-то удобно и экономит время, убирая рутинну.
```
:cl:
qol: Имиалки теперь есть в ограниченном количестве в Наномед Плюс.
/:cl:
```
> Чуть больше удобства с имиалки 

- code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Исправил то что паунс раннера не дерегистрировал сигнал для удаления.
Насрал xd
```
:cl:
fix: Исправил то что паунс раннера не дерегистрировал сигнал для удаления.
/:cl:
```
> Fixes runner pounce not unregistering delete signal properly.

- code/_onclick/hud/screen_objects/menu_text_objects.dm
- code/datums/autocells/explosion.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
```
:cl:
fix: Исправил рантайм при отсутствии клиента от кнопки в лобби.
fix: Исправил рантайм при джебе варриора не по людям.
fix: Исправил рантаймы при воспроизведении звуков взрывов.
/:cl:
```
> Fixes runtimes with explosion sounds, lobby join button and warrior jab punch.

- code/game/objects/items/storage/storage.dm
Насрал, исправил, теперь это работает на 1 iq лучше, вроде теперь все должны быть довольны...
```
:cl:
fix: При клике не вмещаемым предметом, если этот контейнер не был открыт, он откроется.
/:cl:
```
> Storage can be open on click with too big item

- code/__DEFINES/skills.dm
- code/datums/skills.dm
- code/game/objects/items/pamphlets.dm
- code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
- code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Отрубил лапки танк пилотам на управлением мехами, пока не сделали мехов НЕ ЮЗАЕМ.
ноу фанни аловд
```
:cl:
fix: Танкисты не могут управлять мехом
/:cl:
```
> Assault crewman can't controll mech

- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Блинк хантера теперь телепортирует на тайл цели, а не на случайный соседний.
На каждый новый абуз придется кучу говнокода писать. В измененном виде абилка уже проблем доставлять не будет.
```
:cl:
add: Блинк хантера теперь телепортирует на тайл цели, а не на случайный соседний.
/:cl:
```
> Hunter blink change

- code/game/objects/items/reagent_containers/hypospray.dm
- code/game/objects/items/reagent_containers/pill.dm
- code/modules/reagents/reagents/medical.dm
- code/modules/reqs/supplypacks/medical.dm
1) Метаболизация Алкизина равна метаболизации Имидазолина.
2) Заменил в карго крейте таблетки на ИмиАлки, вместо своих полновесных аналогов.
Непонятно, кто вообще кодил Алкизин и Имидазолин.
Они имеют фактически одинаковый эффект, только для разных двух зон головы.
При этом имеют различный метаболизм.
Для излечения стандартного урона по мозгу требуется 20 тиков лечения Алкизину. Это эквивалентно 1u реагента(как мы помним, в таблетке аж 3,5u).
Для излечения стандартного максимального урона по глазам требуется 30 тиков Имидазолина. Это эквивалентно 6u реагента(Как мы помним, в таблетке аж 11,5u).
Какого блин, хуя?
Если сделать их метаболизм равным и сделать равным соотношение 1:1, то в итоге у нас получится 7,5 : 7,5 u реагентов.
При равном метаболизме Алкизину потребуется 4u для лечения …
> Tweak/nerf Alkyzine

- code/modules/projectiles/ammo_datums/bullet/revolver.dm
- code/modules/projectiles/guns/revolvers.dm
Больше модулей на Нигредо, добавил более далёкий полёт пули по сравнению с обычным револьвером, но меньше, чем у снайперок (у них по 40), чтобы можно было использовать его как снайперское оружие, но без ифф и аима. Пуля летит как раз до границы снайперского прицела.
Рофлоган получит больше применений, возможно станет немного более играбельным или хотя бы интересным. Снайперский револьвер с вертикальной рукояткой звучит круто!
```
:cl:
balance: Больше модулей на R-500, в том числе прицелы и рукояти
balance: Пули R-500 летят дальше обычных на 5 тайлов.
/:cl:
```
> Больше модулей на Нигредо

- code/__DEFINES/loadout.dm
- code/__DEFINES/skills.dm
- code/datums/skills.dm
- code/game/objects/items/weapons/blades.dm
- code/modules/mob/living/carbon/human/human_defense.dm
Убрал лок на валирапиру, теперь скилл не требуется, по приказу генерала татарла (роад мап). Блок предаторов теперь зависит не от скилла рапиры а из-за мили скилла
```
:cl:
add: Теперь для использования вали рапиры не требуется скилл
/:cl:
```
> Roadmap - Vali rapir delete skill lock

- code/datums/elements/strappable.dm
- code/modules/mob/mob.dm
Запортил фикс некоторыз багов, теперь будет меньше фантомных предметов, и например, нельзя будет положить застрапленный предмет.
```
:cl:
fix: Привязанные предметы нельзя положить на стол и фантомно размножить.
/:cl:
```
> Port strapable fixes

- code/game/objects/items/stacks/rods.dm
Разбор укрепленного железными прутьями пола на шаттле теперь не оставляет после себя тайл космоса.
```
:cl:
fix: Разбор укрепленного железными прутьями пола на шаттле теперь не оставляет после себя тайл космоса.
/:cl:
```
> Укреплённый пол больше не удаляет пол до базового тюрфа

- code/datums/cinematic.dm
- code/datums/gamemodes/infestation.dm
Заменил `sleep()` на таймеры, что должно чуть улучшить производительность прока, и возможное зависание сервера при проигрывании кино.
```
:cl:
code: Изменил код синематиков, что возможно поможет с зависаниями после их воспроизведения.
/:cl:
```
> Slightly improves cinematics code.

- code/modules/mob/living/say.dm
Раньше, если вы хотели поговорить на бинарном канале или на голопаде, вам приходилось писать ключ канала ТОЛЬКО на английском. Сейчас можно писать ключ на русском.
Не нужно будет переключаться на английский язык чтобы написать ключ. 
```
:cl: kukur
qol: Синтаы и ИИ теперь могут писать ключ для бинарного канала/голопада на русском языке
/:cl:
```
> Синты и ИИ теперь могут писать ключ бинарного канала на русском

- code/modules/mob/living/carbon/human/species/_species.dm
- code/modules/mob/living/carbon/pain.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/carbon/xenomorph/life.dm
Теперь зеленые феромоны работают как защитный приказ людей.
Приказ людей: у СЛа сила 3-1=2, у ФК 4-1=3. То есть СЛ режет входящий урон на 10%. ФК режет на 15%.
Сделаем таже для беносов. Каждый уровень феромонов НЕ влияет на софт армор, и понижает финальный урон на X% за уровень.
- Нет дикого разброса эффективности патронов
- Понятно
- Проще балансить и маров и ксен
```
:cl:qwerty4429
balance: Феромоны защиты дают мультипликативную защиту
/:cl:
```
Сейчас феры короля дают 15 софт армора, будут давать 15% просто мультипликативного.
> Warding Pheromones rework

- code/modules/admin/verbs/chat_commands.dm
Команды теперь возвращают не стринги а `tgs_message_content`
```
:cl:
code: Команды теперь возвращают не стринги а tgs_message_content
/:cl:
```
> Updates tgs commands returning strings instead of `tgs_message_content`

- code/game/objects/items/radio/radio.dm
Если радиопак на спине, и человек говорит в рацию, его будет слышно всегда, при условии что он в пещерах. Также его могут слышать все, в том числе те кто в пещерах, без проблем. Также на радио пак не работают помехи пещер, и сообщение до людей доходит без помех.
```
:cl:
add: Теперь радио пак дает возможность говорить в пещерах, а также люди слышат его носителя если он находится в пещерах.
/:cl:
```
> Радиопак дает возможность говорить в пещерах.

- code/game/objects/structures/barricade.dm
Удалил всратую интеракцию баррикад при взрыве и наличии баррикад на соседних тайлах, которая роняла сервер.
Меньше роняемого сервера.
```
:cl:
del: Удалил всратую интеракцию баррикад при взрыве и наличии баррикад на соседних тайлах, которая роняла сервер.
/:cl:
```
> Deletes shitloop of barricades ex_act.

- code/modules/projectiles/ammo_datums/rocket.dm
- code/modules/projectiles/magazines/specialist.dm
Сандер ХЕ ракет 100 >> 0
Сандер ХИАТ ракет 0 >> 50
Сандер фосфорной ракеты для садара 100 >> 50
ХЕ ракеты наносят некоторый сандер самим взрывом, и то что снаряд расчитанный на доставку взрыв-заряда разрушает оболочкой броню смотрится странно в сравнении ХИАТ ракет, которые эти броню пробивают, и этим урон и наносящие.
Да и ХИАТ ракетам нужен бафф, так как они хлам последний.
Фосфорным ракетам понизил сандер чтобы совпадали с ХИАТ-ами.
```
:cl:
balance: Сандер ХЕ ракет 100 >> 0
balance: Сандер ХИАТ ракет 0 >> 50
balance: Сандер фосфорной ракеты для садара 100 >> 50
/:cl:
```
> Heat rockets now damage sunder, lowers HE rockets sundering.

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Смоляные хаггера больше не стакают липкую резину на одном тайле.
Также добавил свой звук и сообщение для нанесения стамина урона после взрыва липкой резиной.
```
:cl:
fix: Смоляные хаггера больше не стакают липкую резину на одном тайле.
/:cl:
```
> Resin huggers no longer stack sticky resin on 1 tile.

- code/modules/organs/organs.dm
- code/modules/reagents/holder.dm
Микродозинг больше не добавляет +1 реагент к подсчёту реагентов при превышении капа реагентов.
Я думаю что микродозинг имеет свои плюсы и минусы, поэтому пусть будет альтернативой, для тех кто готов страдать этой фигней.
Также это исправит то что таблетки лишний раз дают мультики при употреблении.
```
:cl:
balance: Микродозинг больше не добавляет +1 реагент к подсчёту реагентов при превышении капа реагентов.
/:cl:
```
> Delete microdosing extra counting towards reagent cap.

- _maps/map_files/icy_caves/icy_caves.dmm
На Icy Caves было уменьшено кол-во буров в шаговой доступности друг от друга, чуть скорректирован туман на спавнах ксеноса для крашей, удалено 2 места посадки Кантерберри прямо у диска, добавлено новое место для диска, исправлены несостыковки зон.
Карта должна стать чуть лучше в плане баланса.
```
:cl:
map: На Icy Caves было уменьшено кол-во буров в шаговой доступности друг от друга, чуть скорректирован туман на спавнах ксеноса для крашей, удалено 2 места посадки Кантерберри прямо у диска, добавлено новое место для диска, исправлены несостыковки зон.
/:cl:
```
> Icy Caves tweaks.

- code/modules/client/preferences_ui.dm
Бинды работают с русской раскладкой.
Можно будет не перезаходить в игру с английской раскладкой чтобы поменять бинды, АЛИЛУЯ!!
```
:cl:
fix: Бинды работают с русской раскладкой.
/:cl:
```
> RU keybinds fix

- code/datums/gamemodes/crash.dm
- code/modules/reqs/supplypacks/_supplypacks.dm
- code/modules/reqs/ui/request.dm
На краше теперь нельзя купить оборудование для завода.
Бесконечные ресурсы за 1600 очков выглядит всрато.
```
:cl:
balance: На краше теперь нельзя купить оборудование для завода.
/:cl:
```
> Restricts buying factory equipment on crash.

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Хаггеры теперь умирают от огня, но могут его перепрыгнуть.
На снятие хаггера с лица это не влияет.
Хаггеры теперь умирают если их кидать под танк.
Убийство хаггером огнём выглядит логично.
Нельзя будет абузить танки для заражения маров хаггерами.
```
:cl:
balance: Хаггеры теперь умирают если их кидать под танк.
balance: Хаггеры теперь умирают от огня, но могут его перепрыгнуть. На снятие хаггера с лица это не влияет.
/:cl:
```
> Facehuggers now can be killes by fire, but they can leap over it.

- code/game/objects/obj_defense.dm
- code/modules/projectiles/projectile.dm
Удалил воспроизведение несуществующего звука при попадании пули по объектам.
Нигде не используется, лишний прок.
```
:cl:
code: Удалил воспроизведение несуществующего звука при попадании пули по объектам.
/:cl:
```
> Deletes unused playsound in obj bullet_act.

- _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
- _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
- _maps/map_files/Research_Outpost/Research_Outpost.dmm
На Research Outpost и Orion Outpost были добавлено спавнеры травы для ксеносов.
Чуть играбельнее карты.
```
:cl:
map: На Research Outpost и Orion Outpost были добавлено спавнеры травы для ксеносов.
/:cl:
```
> Weedifies Research Outpost and Orion Outpost.

- code/game/objects/structures/teleporter.dm
Телепортеры теперь бибикают и высвечивают текстовое сообщение при использовании телепортером внутреннего заряда батареи для телепортации
Также добавлено связывание телепортеров, если один из них уже установлен.
Напоминалка для смены батареи. Защита от балбеса.
```
:cl:
qol: При использовании внутреннего заряда батареи для телепорта, телепортеры теперь бибикают и высвечивают сообщение об использовании заряда батереи.
qol: Теперь можно слинковать телепортеры, если один из них уже установлен.
/:cl:
```
> Teleporter now beeps if the internal charge is used for teleportation. Added linking teleporter in hand to a deployed teleporter.

- code/__DEFINES/loadout/gear/field_commander.dm
- code/__DEFINES/loadout/gear/leader.dm
- code/__DEFINES/loadout/gear/marine.dm
- code/__DEFINES/loadout/gear/smartgunner.dm
- code/datums/storage/subtypes/belt.dm
- code/game/objects/machinery/vending/marine_vending/uniform.dm
- code/modules/reqs/supplypacks/clothing.dm
M344 pattern ammo load rig теперь бесплатный и в общем доступе
повышена вместимость до 5 слотов
марин бафф
```
:cl:
add: M344 pattern ammo load rig in The Surplus Clothing Vendor
/:cl:
```
> M344 pattern ammo load rig in marine vendor

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Варриор теперь не может прокидывать маров за туман краша.
```
:cl:
add: Варриор теперь не может прокидывать маров за туман краша.
/:cl:
```
> Restricts warrior from using grapple toss inside crash fog.

- code/modules/reagents/chemistry/reagents/medical.dm
Имиалки больше не лечит токс урон.
Никаких объективных причин почему имиалки лечило бы токс урон.
```
:cl:
balance: Имиалки больше не лечит токс урон.
/:cl:
```
> Imialky no longer heals tox damage.

- code/game/objects/machinery/vending/marine_vending/weapon.dm
Отделены штурмовые винтовки и стандартные винтовки в вендорах
Визуально разделяет "очередные арки" и винтовки
```
:cl:
qol: Отделены штурмовые винтовки и стандартные винтовки в вендорах.
/:cl:
```
> Separate assault rifles and standart rifles

- code/_onclick/hud/screen_objects/screen_objects.dm
Исправил то что ксеноморфы могли украсть предметы из контейнеров если нажимали на сам слот инвентаря, вместо предмета.
Для отыгрыша руни нужно чтобы было примо, да.
```
:cl:
fix: Исправил то что ксеноморфы могли украсть предметы из контейнеров если нажимали на сам слот инвентаря, вместо предмета.
/:cl:
```
> Restricts xenos from stealing items from storages.

- code/game/objects/machinery/doors/poddoor.dm
- code/game/objects/machinery/fax.dm
- code/modules/paperwork/photocopier.dm
Броня створок и ставней уменьшена для пуль и лазеров со 100 до 90.
Фотокопировальную машину и факс теперь можно сломать за ксеноса.
Стены можно спокойно сломать с помощью пуль, но створки при этом можно сломать только с помощью кислоты или взрыва.
Факс и фотокопировальный аппарат просто мешаются ксеносам, из-за того что их нельзя нормально сломать, но при этом можно расстрелять, расплавить или взорвать.
```
:cl:
balance: Броня створок и ставней уменьшена для пуль и лазеров со 100 до 90.
balance: Фотокопировальную машину и факс теперь можно сломать за ксеноса.
/:cl:
```
> Nerfs poddoors and shutters bullet and laser armor. Photocopier and fax machine are now slashable.

- code/modules/reagents/chemistry/reagents/toxin.dm
У Озеломелина теперь нету лимита токс урона в 40 единиц.
Ксенобафф.
```
:cl:
balance: У Озеломелина теперь нету лимита токс урона в 40 единиц.
/:cl:
```
> Ozelomelyn now doesn't have a damage cap.

- code/datums/cinematic.dm
- code/datums/gamemodes/infestation.dm
Время ожидания после анимации взрыва ядерки уменьшено с 30 секунд до 15.
Исправил отображение взрыва ядерки на краше.
```
:cl:
qol: Время ожидания после анимации взрыва ядерки уменьшено с 30 секунд до 15.
fix: Исправил отображение взрыва ядерки на краше.
/:cl:
```
> Fixes crash cinematic. Makes cleanup time for cinematics 15 seconds.

- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Убран нейроплевок у претора.
Бесполезная абилка после вывода нейротоксина, которую юзают только новайсы.
Сама абилка будет переработана под стрейн сента.
```
:cl:
del: Убрал возможность выбрать нейроплевок у претора
/:cl:
```
> Remove toxin spit at the praetorian
