code/_globalvars/lists/mobs.dm

Позволит потестить его в Вальгалле.

Adds predalien to mob list.

---

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm

Цена абилки повышена на 50 плазмы, но теперь она тушит зажженные флаера.
Бесполезная абилка, станет чуть полезнее.
:cl:
balance: Найтфолл Кинга теперь тушит зажженные флаера.
/:cl:

Nightfall extuinguishes active flares.

---

code/game/objects/items/explosives/bombvest.dm
code/game/sound.dm
code/game/turfs/space.dm
code/game/turfs/space/transit.dm
code/game/turfs/turf.dm
code/modules/organs/limbs.dm

Падение наносит 300 мили урона и 300 урона бомб урона, то есть в том же б17 это можно пережить если в крови есть химия, ну и жирные ксеносы по-типу крашеров и квины переживут падение.
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/8a7f4d04-e884-497b-8442-9584daaa50a6
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/8392d28d-5337-40d0-8347-a161b88aa372
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/7b31959e-aaa9-4cdf-93bf-cff1e9718a3d
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/a2837a60-86f2-4a55-bb87-ddaf07bc6cc4
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/93882977/2702436c-53ff-4ec2-b9fd-ae390760b677 …

Space transit tiles now send atoms flying to the ground.

---

code/modules/projectiles/gun_system.dm
code/modules/projectiles/mounted.dm

порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/16165
```
:cl:
add: Guns can be fired offhand with right click
/:cl:
```

Off-hand shooting

---

code/game/objects/items/storage/storage.dm

порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/15609
```
:cl:
qol: Clicking on a storage with an item that cannot be inserted in said storage will open it
/:cl:
```

Storage opening QOL

---

code/_onclick/hud/radial.dm
code/modules/radial/radial_body_select.dm

порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/15516
```
:cl:
qol: Radial menus for applying medicine will now fit all LIMBS on a ring instead of having 2 pages.
/:cl:
```

Makes the radial menu for all medicine fit all limbs.

---

code/game/objects/items/storage/storage.dm

порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/15610
```
:cl:
qol: Clicking on an opened storage will close it
/:cl:
```

Storage closing QOL

---

code/__DEFINES/cooldowns.dm
code/__DEFINES/mobs.dm
code/_onclick/hud/screen_objects/screen_objects.dm
code/datums/keybinding/carbon.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living_verbs.dm

Порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/14898 и https://github.com/tgstation/TerraGov-Marine-Corps/pull/15076
Нет нужды закликивать рест, во избежание получения по-лицу во время отдыха.
```
:cl:
qol: Ксеносы в ресте теперь встают мгновенно, но после 2-ух секундного кд.
/:cl:
```

Resting rework.

---

code/game/objects/structures/window.dm
code/game/objects/structures/window_frame.dm
code/modules/power/apc/apc.dm

Скилл ишью от меня так как забыл переменную у рамы для окна.
Скилл ишью от тех кто переносил модульные взрывы.
```
:cl:
fix: Рамы для окон на Талосе теперь отображаются.
fix: Апц и окна теперь нормально взрываются.
/:cl:
```

Fixes Talos window frames and also window and apc ex_acts.

---

_maps/map_files/Talos/TGS_Talos.dmm
code/game/objects/structures/prop.dm

До
После
Чуть красивее и удобнее, наверное.

Tweaks talos cargo.

---

code/game/objects/structures/reagent_dispensers.dm

Фикс рантайма. После взрыва и удаления себя, фуелтанк пытается получить урон, но получать его нечему.
Фикс.
```
:cl:
fix: Исправил рантайм связанный со взрывом фуелтанка.
/:cl:
```

Fixes fuel tank runtime.

---

_maps/map_files/Talos/TGS_Talos.dmm

Удалил лишние интеркомы в месте конференций для маринов.
Распределил топливо для об равномерно по стойкам.
Убрал одну бочку с прохода под карго.
Окна ИИ теперь на одном тайле вместо 4-ех разных.
Переместил стулья для посетителей в кабинетах ФК и КЛ-а.
Переместил хлам со стола у кровати ФК в шкаф ФК.
Чуть красивее и удобнее.

Talos little tweaks.

---

code/controllers/subsystem/vote.dm

Теперь нельзя голосовать за граунд мапу, на которой прошёл раунд.
Вариативность?
```
:cl:
add: Теперь нельзя дважды играть на одной и той же граунд мапе, так как она не появляется в голосовании.
/:cl:
```

Restricts ground map vote from voting the current map.

---

code/__DEFINES/cooldowns.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm

Существует проблема, в виде того что при взрыве (зачастую в эпицентре) моба выталкивает на другой турф, и уже другая взрывная волна наносит доп. урон мобу.
Это конечно костыль, но пусть будет так пока не придумаю чего получше. Лагов немножко прибавит, но наверное не сильно.

Attempt to prevent double explosion damage from explosion throws into explosion waves.

---

code/game/objects/structures/window.dm

Окна шлюпок для эвакуации теперь не выглядят так будто построены вокруг стен корабля.
Без вот этого:
```
:cl:
fix: Окна шлюпок для эвакуации теперь не выглядят так будто построены вокруг стен корабля.
/:cl:
```

Changes smoothing groups of escape shuttle windows, so it doesn't smooth with ship walls.

---

_maps/map_files/Talos/TGS_Talos.dmm

Починил отстутствующие и удалил лишние трубы на Талосе.
```
:cl:
fix: Исправлены трубы на Талосе.
/:cl:
```

Fixes pipes on Talos.

---

code/game/objects/items/defibrillator.dm

Дефибриллятор теперь не обнуляет окси урон, а хилит по той же формуле что и остальной урон.
Сделает дексалин полезнее, а дексалин+ не только как добавку в синомикс. Возможно сделает воскрешение маров без корпса под рукой немного проблематичнее.
```
:cl:
balance: Дефибриллятор теперь лечит окси урон по формуле лечения остального урона.
/:cl:
```

Defibrillator now heals oxy damage on the same formula as other damages.

---

code/game/objects/structures/xeno.dm
code/game/turfs/walls/resin.dm

Лориансс сделал какую-то максимально не интуитивную хуйню, и новичкам нужно звать на помощь чтобы выбраться из застройки ибо самый интуитивный вариант не работает.
Новичкам будет легче постигать игру.
```
:cl:
qol: Ломание структур ксеносов теперь опять на харм интент.
/:cl:
```

Reverts lorians schizophreny.

---

code/datums/status_effects/xeno_buffs.dm

Фид насрал.
```
:cl:
fix: Фист горжера теперь работает как и должно.
/:cl:
```

Fixes gorger's feast

---

code/game/turfs/walls/wall_types.dm

Добавляет вот это:
И это:
И даже вот это:
И заменяет вот это:
На вот это:
```
:cl:
imageadd: Добавлены новые лобби арты.
/:cl:
```

Adds some new lobby arts.

---

code/game/turfs/space/transit.dm

Фиксит вот это: 
https://github.com/user-attachments/assets/bc8a51d0-b4d0-45a8-9e90-33306641a8a1
```
:cl:
fix: Выталкивание человека с шахидкой с борта, теперь не взрывает тебя.
/:cl:
```

Fixes misusage of `usr` in boomvest falling code.

---

_maps/map_files/Talos/TGS_Talos.dmm

Починил раковины, диспосал трубы на первом этаже, провода, апц в офисе пилотов, двойные окна на мостике, добавил нексус вендор сл-у дельты и чутка переделал его комнату, провёл трубы к некоторым мусоркам, мусорки с 1-го этажа теперь ведут через космос на 2-ой этаж к мусоропереработчику.

Talos fixes.

---

code/datums/actions/order_action.dm
code/modules/screen_alert/command_alert.dm

Теперь нельзя кейбиндами срать в радио если ты не лидер.
```
:cl:
fix: Исправлен обход ограничений приказов и бафов через кейбинды.
/:cl:
```

Fixes bypassing order limitations with keybinds.

---

code/datums/jobs/job/fallen.dm
code/datums/jobs/job/marines.dm
code/datums/jobs/job/shipside.dm
code/datums/jobs/squads.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_ui.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/new_player/preferences_setup.dm
tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx

Исправлено то что ты не мог зайти за робота, без выбранного сквада.
Добавлена отдельная настройка имени для робота.
Почищен хлам.
```
:cl:
add: Добавлена настройка имени для сквад роботов.
fix: Исправлено то что ты не мог зайти за сквад робота без выбранного отряда.
/:cl:
```

Adds squad robot name specific settings. Fixes that you can't join as robot without squad chosen.

---

code/modules/client/preferences_savefile.dm

Порядок вытягивания теперь будет сохраняться.
```
:cl:
fix: Порядок вытягивания теперь сохраняется.
/:cl:
```

Fix draw order not saving (#16128)

---

code/_globalvars/lists/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Почистил  и рассортировал по алфавиту списки пулла, добавил в него варлока и хм-а.
```
:cl:
fix: Теперь опять можно стать хм-ом или варлоком.
/:cl:
```

Readds warlock and hivemind to evolution pull.

---

_maps/interiors/tank.dmm
_maps/map_files/Talos/TGS_Talos.dmm

Фикс говна с телекомами в танке и апц
На Талосе переработал сквадрумы в более удобный формат
Никак
```
:cl:
add: Сквадрумы переработаны
fix: Исправлено отсутствие связи в танке/апц
/:cl:
```

some chage TalOZ, tele in tank

---

code/game/atoms/atom_movable.dm
code/modules/vehicles/__vehicle.dm
code/modules/vehicles/_hitbox.dm
code/modules/vehicles/armored/_multitile.dm

Фиксы телепортации на танке

---

code/modules/reagents/reagents/medical.dm

I fix Ifex 

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

я не учёл что урон и так учитывает рейдж павер

Ravager buff

---

code/_globalvars/admin.dm
code/datums/gamemodes/_game_mode.dm

respawntime

---

code/__DEFINES/objects.dm
code/modules/reqtorio/assembly_crafts.dm
code/modules/reqtorio/craft_components.dm
code/modules/reqtorio/machines.dm

фикс https://discord.com/channels/1235677154084126861/1277166834633936898

AssSembler fix

---

code/modules/reqs/supply.dm

Radiopack fix

---

code/modules/mob/living/carbon/xenomorph/death.dm

Ксеносы теперь не остаются с худами для остальных ксеносов после смерти.
```
:cl:
fix: Худы ксеносов теперь обновляются после их смерти.
/:cl:
```

Xenos now update hud on death.

---

code/modules/reagents/reagents/medical.dm

peridaxon fix

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Добавил назад то что по глупости удалил

Fixes zoom in formula.

---

tgui/packages/tgui/interfaces/Assembler.js
tgui/packages/tgui/interfaces/MarineDropship.js
tgui/packages/tgui/interfaces/Mecha/MechStatPane.tsx
tgui/packages/tgui/interfaces/VehicleSupply.tsx
tgui/packages/tgui/interfaces/Vending.tsx

фикс линтеров тгуи

---

code/modules/vehicles/_hitbox.dm

Порт [#15984](https://github.com/tgstation/TerraGov-Marine-Corps/pull/15984)

Фикс танка 2

---

code/modules/projectiles/sentries.dm

Turrets runtime fix

---

code/datums/gamemodes/distress.dm
code/datums/gamemodes/nuclear_war.dm
code/datums/jobs/job/survivor.dm
code/datums/skills.dm
code/game/objects/items/radio/radio.dm
code/game/objects/items/stacks/stack.dm
code/modules/clothing/suits/armor.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

вернул возможность спавна за сурва
сделал дефолтные навыки cqc и мили для сурвов (а чё он за 3 удара траву ломал)
добавил сурвам гарнитуру (работает как радио)
откатил нерф скорости строительства фида
броне сурвов добавил слоты для предметов
травой теперь нельзя срать там где нельзя строить до створок

 survivals

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm

во время удаления сандера забыл убрать регенерацию кожи

Kills Regenerate Skin ability

---

code/game/turfs/space/transit.dm

Исправил то что при сбрасывании шкафчиков в космос, шкаф бросало на землю, а содержимое оставляло в космосе xd
```
:cl:
fix: Исправлено то что при падении из космоса, шкафы оставляли содержимое в космосе.
/:cl:
```

Fixes `handle_airdrop` not working for closets properly.

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

Понижена цена обливиона с 1000 до 500 пси очков.
Что может пойти не так.
```
:cl:
balance: Понижена цена обливиона с 1000 до 500.
/:cl:
```

Lowers oblivion price from 1000 to 500.

---

code/modules/reagents/reagents/medical.dm

наниты теперь регенят кости да...
убрал нанесение урона во время адаптации потому что наниты с бктт несовместимы и лечить нечем
теперь во время регена органов и костей выделяется больше токсинов и тратятся наниты

bone breake

---

code/modules/vehicles/unmanned/unmanned_vehicle.dm

Теперь нельзя за ИИ использовать машинки в Вальгалле.
```
:cl:
fix: Машинки в вальгалле теперь не появляются в меню контроля ИИ.
/:cl:
```

Fixes unmanned vehicles in valhalla adding to the ai controlled list.

---

code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/ai/ai_behaviors/xeno/xeno.dm
code/modules/ai/presets/xeno_presets.dm

Черри-пикнуть не смог потому вот так.
У всех ии мобов кроме битлов, мантисов и раважирова теперь есть отметка хп, после которого они убегают.
ИИ чуть умнее.
```
:cl:
add: Ксено ии всех ксеносов кроме биттлов, мантисов и равагеров теперь убегает при низком здоровье.
/:cl:
```

Makes xeno ai's less suicidal.

---

code/__DEFINES/loadout.dm
code/datums/components/riding/riding_vehicle.dm
code/game/objects/machinery/mortar.dm

1. Бафнул скорость байка с 2 до 1.5
2. Добавил байк и коляску к нему в вендор за поинты
3. Поменял в покупном наборе Катюши одну обычную ракету на газовую

up bike, nerf rmls in marinvend

---

code/modules/vehicles/motorbike.dm

Motorbike buff

---

code/__DEFINES/mobs.dm
code/datums/status_effects/xeno_buffs.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm

У равагера рейдж и здоровье теперь обновляются мгновенно при получении и нанесении урона
Дрону вернул прежние статы линка

Rav and Drone fixes

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/LV624/LV624.dmm
_maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
_maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
_maps/map_files/Research_Outpost/Research_Outpost.dmm
_maps/map_files/deltastation/deltastation.dmm
_maps/map_files/desparity/desparity.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm
_maps/map_files/icy_caves/icy_caves.dmm

Добавляет базовые баррикады в посадочных зонах на всех играбельных картах

Стандартные баррикады

---

_maps/map_files/Talos/TGS_Talos.dmm

Добавил спавнер для офицера тада.
Заменил двери мехвода в комнате пилотов на двери для пилотов.
```
:cl:
fix: Исправил закрытые для пилотов двери в жилище пилотов.
/:cl:
```

Fixes pilot bunks on Talos.

---

code/modules/mob/living/living_health_procs.dm

Поставил `?` для проверки на наличие желудка, перед попыткой его очистить.

Fixes revive stomach runtime.

---

tgui/packages/tgui/interfaces/EscapePod.js

Кнопка теперь работает.
```
:cl:
fix: Кнопка в эвакуционной шлюпке теперь работает.
/:cl:
```

Escape pod button fix (#16467)

---

code/_onclick/xeno.dm

вот это вот
https://github.com/user-attachments/assets/c6029ecf-529a-4e78-bf62-8002bd192751

Xeno extinguishing fire 

---

code/datums/gamemodes/points_defence.dm
code/game/objects/items/radio/headset.dm
code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

подчистил код поинт дефенса
выпилил на время наземные телекомы, потому что от них одни баги

Points Defence clean up

---

code/game/turfs/walls/resin.dm

Исправляет фичу, когда ксены не могли разрушить свои же стены

Meleeproof walls fix

---

code/__DEFINES/atom.dm
code/__DEFINES/dcs/signals.dm
code/game/atoms/_atom.dm
code/game/objects/effects/aliens.dm
code/game/objects/items.dm
code/game/objects/machinery/deployable.dm
code/game/objects/objs.dm
code/game/objects/structures/barricade.dm
code/game/objects/structures/dropship_equipment.dm
code/game/turfs/open.dm
code/game/turfs/turf.dm
code/game/turfs/walls/walls.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/projectiles/mounted.dm
tgmc.dme

Код чуть чище и возможно менее хард-делитный.
```
:cl:
refactor: Переделан код кислоты.
/:cl:
```

Acid code cleanup.

---

code/game/objects/items/tools/shovel_tools.dm

Острая лопата 60 -> 90 = Мачете

---

code/__DEFINES/is_helpers.dm
code/game/objects/items/weapons/misc.dm
code/modules/projectiles/gun_helpers.dm

Теперь нету попытки тактически перезарядить паверпак при попытке подключиться к нему.
```
:cl:
fix: Подключение к паверпакам теперь работает как должно.
/:cl:
```

Fixes tactical reload intercepting worn magazines.

---

code/__HELPERS/logging/attack.dm
code/__HELPERS/mobs.dm
code/controllers/subsystem/lighting.dm
code/controllers/subsystem/minimaps.dm
code/datums/jobs/squads.dm
code/game/atoms/atom_movable.dm
code/game/objects/items/motion_detector.dm
code/game/objects/items/weapons/blades.dm
code/game/objects/items/weapons/weapon.dm
code/game/objects/machinery/computer/camera_advanced.dm
code/game/objects/machinery/hologram.dm
code/game/objects/machinery/telecomms/broadcasting.dm
code/game/objects/structures/droppod.dm
code/game/objects/structures/teleporter_array.dm
code/game/sound.dm
code/modules/condor/cas_shuttle.dm
code/modules/keybindings/bindings_atom.dm
code/modules/mapping/map_template.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/silicon/ai/freelook/README.md
code/modules/mob/living/silicon/ai/freelook/eye.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/projectile.dm
code/modules/projectiles/sentries.dm
code/modules/vehicles/mecha/mecha_mob_interaction.dm
code/modules/xenomorph/tunnel.dm
tgmc.dme

ИИ теперь отображается слышимая из камер речь ввиде рунчата.
Призраки теперь могут нажав по точке на миникарте телепортироваться туда.
Вроде как: 
- фиксит фантомные иконки при смене з-левела в танке.
- фиксит проблемы с освещением в виде чёрных квадратов на Талосе.
- фиксит кучу рантаймов.
Удобство и меньше сломанного хлама.
```
:cl:
qol: ИИ теперь видит слышимую через камеру речь через рунчат.
qol: Призраки теперь могут телепортировать В выбранную на миникарте точку на миникарте.
fix: Вроде как исправлены фантомные иконки при смене з-левела в танке.
fix: Вроде как исправлены черные квадраты на Талосе.
/:cl:
```

Ports qols & fixes: 14677, 14822, 15793, 15814, 15855, 16153

---

code/modules/reqtorio/assembly_crafts.dm

Исправлены неточности в рецептах завода.
```
:cl:
fix: Исправил неточности в рецептах завода.
/:cl:
```

Factory fixes.

---

code/game/turfs/space/transit.dm

Удаляет урон по мобам от падающих из космоса предметов.
Слишком весело.
```
:cl:
del: Удалил урон по мобам от падающих из космоса предметов.
/:cl:
```

Deletes death from above.

---

code/datums/components/suit_autodoc.dm
code/game/objects/items/scanners.dm

Валькирия теперь проверяет содержимое желудка перед вводом реагентов для предотвращения передоза.
Реагенты в желудке кол-во которых превышает лимит передоза, теперь подписаны красным.
```
:cl:
fix: Валькирия теперь проверяет содержимое желудка перед вводом реагентов для предотвращения передоза.
fix: Реагенты в желудке кол-во которых превышает лимит передоза, теперь подписаны красным.
/:cl:
```

Suit autodocs now check storage contents before injecting. Health analyzer now properly makes overdosed reagents in stomach red.

---

tgmc.dme

Includes cargo category of medical.

---

_maps/map_files/Talos/TGS_Talos.dmm

Теперь экипаж танка и апц не замурованы.
```
:cl:
fix: Экипаж танка и апц теперь могут выйти из комнаты пилота.
/:cl:
```

Fixes transport and assault crewman being locked in pilot bunks.

---

code/modules/mob/living/silicon/ai/ai.dm

Фикс ГЦ ИИ

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm

Добавляет спец. стены ХМу

---

_maps/shuttles/escape_shuttle.dmm

Криокапсулы на эвакуационном шаттле теперь смотрят в правильную сторону.
Красивенько.

Cryopods on escape shuttle now look in the right direction.

---

code/_onclick/adjacent.dm
code/game/objects/items/storage/internal.dm

Фикс лагов с танками, наверное.

Adjacency runtime fix (#15218)

---

code/modules/shuttle/on_move.dm

На локалке работает, проверим как будет на сервере.
```
:cl:
fix: Исправил ломание труб после отлёта тада.
/:cl:
```

Probably fixes tad breaking pipes.

---

code/game/objects/effects/countdown.dm

Будет обновляться 1 раз в секунду

Понижает частоту обновления таймера способностей

---

code/datums/gamemodes/_game_mode.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_ui.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/mob_defines.dm
code/modules/mob/mob_verbs.dm
tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx

Reverts PMC-Unga-Marines/RuTGMC-Reborn#194

Revert "Respawn Alerts"

---

code/modules/power/lighting.dm
code/modules/vehicles/powerloader.dm

За основу взят этот пр: https://github.com/tgstation/TerraGov-Marine-Corps/pull/8018
Возможно и вправду сработает.

Maybe fixes sd lights lag.

---

code/game/turfs/walls/walls.dm
code/modules/projectiles/projectile.dm

Урон от пуль по стенам уменьшался бронёй 2 раза подряд. Теперь это пофикшено.

Ещё один фикс стен

---

code/__DEFINES/loadout.dm
code/datums/components/riding/riding_vehicle.dm
code/modules/clothing/modular_armor/attachments/chest_plates.dm
code/modules/clothing/modular_armor/jaeger.dm
code/modules/clothing/modular_armor/xenonauten.dm
code/modules/projectiles/ammo_datums/bullet/shotgun.dm
code/modules/projectiles/ammo_datums/energy.dm
code/modules/reqs/armor.dm

1. Убрал сандер у лазерных пушек и сх15. Их у него не должно было быть изначально.
2. Поднял урон/пенетру пушкам с вырезанным сандером по хз какой-то ебанутой формуле Ксенона
3. Понижена скорость байка. В тестовом формате.
4. Мимир2 возвращен в игру
5. Тюр2 шлем добавлен в ящик карго
6. Всей броне маров снижен бомбармор до 10/20/30 соотв.

nerf and twix

---

code/modules/organs/wound.dm

Преды насрали.
```
:cl:
fix: Квикклот теперь приостанавливает внутренние кровотечения, как и должно.
/:cl:
```

Fixes quickclot not stopping internal bleedings.

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

Наносит больше урона по танку и другим объектам
Теперь переворачивает турели

Бафф разбега крашера

---

code/modules/projectiles/projectile.dm

Можно стрелять из за плеча союзников, марин баф? больше френдли фаера с дробовика? ДА!!
https://github.com/user-attachments/assets/4708fe02-0094-4f77-bc4d-c37bbbf0a429

shooting from behind the shoulder

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Возможно ничего не делает ¯\_(ツ)_/¯
Прок для удаления проков есть, но нигде не используется. Так же не смог найти удаление вербов при удалении моба. 
Возможно это также стоит сделать для верба лежания у людей.

Attempt to fix some of xeno harddels.

---

_maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
code/game/turfs/turf.dm

Спустя 3.5 года на ЛВ теперь почти играбельна южная половина карты, ахуеть
Бенотрава теперь растет на всей траве

Бенотрава на ЛВ теперь растет везде

---

_maps/map_files/Talos/TGS_Talos.dmm

Двери в теха теперь требуют лишь доступ в инженерию, а не какой-то всратый набор из доступа в логистику, медбей и мостик.
Двери в медбее ведущие к капсуле клонов, теперь могут открываться всеми.

Fixes medbay and maint doors on Talos.

---

code/game/objects/items/weapons/blades.dm

Рапиру и вали рапиру теперь можно расплавить.
Валиёбы будут страдать.
```
:cl:
balance: Рапиры теперь плавятся.
/:cl:
```

Officer swords are now acidable.

---

code/modules/clothing/glasses/night.dm

Роботы теперь могут надеть БЕ-47
Я хуй знает, остальные пнв они же могут надеть.
```
:cl:
balance: Роботы теперь могут надеть БЕ-47.
/:cl:
```

Robots can now wear BE-47.

---

code/game/objects/items/misc.dm
code/game/objects/items/toys/toys.dm

Плюшевые игрушки теперь пищат при использовании в руке.
Немного уменьшил кол-во копипасты.
Никак, но это прикольно.
```
:cl:
add: Плюшевые игрушки теперь пищат при использовании в руке.
/:cl:
```

Plushes now play sound on attack_self.

---

code/game/objects/structures/droppod.dm

Без понятия поможет ли это, но попытка не пытка.

Attempt to fix droppod harddels.

---

code/game/objects/items/pamphlets.dm

листочек для заряжающего теперь спавнится + портировал макс скилл с офов

pamphlet fix

---

code/modules/organs/organs.dm

Добавил назад случайно удаленное взаимодействие почек с фрейром.

Fixes freyr not working.

---

code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/structures/razorwire.dm

При разборе колючки с хп более половины дается колючая леска.
При поломке даётся 1 род.
Починка колючки металлом теперь чинит 60% вместо 30%, чтобы это было хоть как-то выгодно.
Взаимодействие с грабом передвинуто в граб интеракт.
Также убран разный эффект в зависимости от интента, и объединен в один.
Теперь им сможет воспользоваться варриор.
Немного почистил код.
Нельзя будет получать из разрушения колючки, больше чем в неё вложил.
```
:cl:
balance: При разборе колючая проволка теперь даёт 1 колючую леску.
/:cl:
```

Razor wire consistency.

---

code/__HELPERS/unsorted.dm

```
:cl:
add: Добавил новые механики или изменил геймплей.
add: Добавил больше вещей.
del: Удалил старые вещи.
qol: Сделал что-то более простым в использовании.
balance: Изменил баланс некоторых вещей.
fix: Исправил некоторые вещи.
soundadd: Добавил пару крутых звуков.
sounddel: Удалил пару старых звуков.
imageadd: Добавил новые спрайты или изменил старые.
imagedel: Удалил некоторые спрайты.
spellcheck: Исправил несколько опечаток.
code: Изменил некую составляющую кода.
refactor: Переделал код в лучшую сторону.
config: Изменил настройки конфига.
admin: Что-то изменил в механиках для админов.
server: Что-то, в чем должны разбираться владельцы сервера.
/:cl:
```

Fix wrong 515 regex (#14648)

---

code/game/objects/items/explosives/grenades/grenade.dm
code/game/objects/items/explosives/grenades/marines.dm
code/modules/predator/smartdisc.dm

Предположительно это взаимодействие нагружает сервак.
```
:cl:
del: Удалил звук падения гранаты, во имя оптимизации.
/:cl:
```

Removes grenade hit sound.

---

code/modules/requisitions/fulton.dm
code/modules/requisitions/supply_export.dm

Добавляет проверку на оживляемость тиммейта перед продажей его фултоном. Загрифить всё еще можно, если отрубить голову.
Также исправил маленький рантайм.
Меньше тильта от слепых тиммейтов, продавших твою тушу.
```
:cl:
fix: В карго теперь нельзя зафултонить воскрешаемых тиммейтов.
/:cl:
```

Adds fulton dnr check. Also small runtime fix.

---

code/datums/gamemodes/last_stand.dm

Теперь можно использовать Вальгаллу на Ласт Стенде.
```
:cl:
fix: Исправлен спавн Вальгаллы на Ласт Стенде.
/:cl:
```

Fixes valhalla on Last Stand.

---

code/modules/admin/smites/brain_damage.dm
code/modules/surgery/brainrepair.dm
code/modules/surgery/eye.dm

Операция на глазах и мозгу теперь нормально обновляет урон органам, то есть не нужно после операции давать пациенту имидазолин/алкизин.
Чуть почистил код.
```
:cl:
fix: Операция на мозгу и глазах теперь нормально обновляют статус органов.
/:cl:
```

Fixes brain surgery not updating brain damage properly. Same with eyes.

---

code/__HELPERS/icons.dm

Теперь нету рантайма при загрузке.

Fixes dummy icon runtime. (#14756)

---

code/modules/clothing/modular_armor/attachments/cape.dm
code/modules/clothing/modular_armor/attachments/modules.dm

Теперь можно надеть плащ на уже одетую униформу.
Удобство.
```
:cl:
qol: Теперь можно надеть плащ на уже одетую униформу.
/:cl:
```

Makes Chameleon Badge, Cape, Kama, and Reflective Belt Easier to Equip (#14741)

---

code/game/turfs/walls/resin.dm
code/modules/projectiles/guns/flamer.dm

У пуленепробиваемой стены броня повышена 100>150 (оказывается у пуль есть бронепробитие и оно работает)
Огонь из огнемёта теперь не проходит сквозь огнеупорную стену

Бафф новых стен

---

code/modules/reqs/weapons.dm

Скилл ишшуй.
```
:cl:
fix: Исправлено отсутствие СР-81 в карго.
/:cl:
```

Fixes sr-81 in cargo.

---

code/__DEFINES/mobs.dm
code/modules/reagents/reagents/toxin.dm

трансвитокс теперь не хилит бёрн, а просто наносит токс

TRANSVITOX

---

code/modules/organs/wound.dm
code/modules/reagents/reagents/medical.dm

убрал харм от внутряка тк это вприницпе влияло только на наниты
бафнул реген нанитов до 3 (мне кажется это более интересным вариантом чем меньшее потребление крови тк можно будет просто вечно ходить под изотоником + сахар, но если что поменяю)

nanites some buffs

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

hunter nerf

---

code/modules/xenomorph/spawner.dm
tgmc.dme

Includes spawner in the .dme

---

code/game/objects/items/scanners.dm
tgui/packages/tgui/interfaces/MedScanner.js

сканер теперь показывает в какой конечности внутряк

internal bleeding scan

---

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm

Добавил кучу спавнеров для травы на Призон Стейшн.
Также добавил спавнеры для туннелей.
Карта станет чуть играбельнее для ксен.

Properly weeds Prison station, also adds tunnel spawners.

---

code/__byond_version_compat.dm
code/controllers/globals.dm
dependencies.sh

Поднял версию бйонда в дефайнах.
Давно пора.

Updates byond defines.

---

code/controllers/configuration/entries/general.dm
code/controllers/subsystem/statpanel.dm
code/modules/admin/fun_verbs.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/clans/client.dm
code/modules/client/client_defines.dm
code/modules/tgui_input/say_modal/modal.dm

Play Internet Sound  тгуи панельки теперь не закрываются от времени.
Переместил все вары для клиента, не находящиеся в `client_defines` в него.
Поменял упоминания `youtube-dl` на `yt-dlp`, конфиг тоже, надеюсь смогу его нормально поменять потом.
Также заменил `dead_mob_list` на 'observer_list` так как это имеет чуть больше смысла, хоть и всё еще почти никакого, чем играть музыку мобам без клиента.
Удобство, чуть чище код.

Updates play internet sound.

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/15124
вот это

Xeno spit is unstaggerable

---

code/controllers/subsystem/vote.dm

Fixes innate/vote harddel.

---

code/datums/autocells/explosion.dm

Теперь не будут лагать так сильно

Cellauto explosions fix

---

code/game/objects/structures/dropship_equipment.dm

Закомментил неиспользуемый огрызок, который можно купить в фабрикаторе, и проебать очки.

Comments unused bomb pod.

---

code/datums/autocells/explosion.dm
code/game/objects/effects/effect_system/smoke.dm
code/game/objects/items/explosives/grenades/grenade.dm
code/modules/power/apc/apc.dm

Исправил 3 рантайма.
Также при удалении волна взрыва теперь обнуляет список взорванных атомов. Не уверен правда что это хоть на что-то повлияет, но пусть будет.

Fixes 3 runtimes.

---

code/game/objects/effects/overlays.dm
code/modules/mob/death.dm
code/modules/mob/living/brain/death.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/xenomorph/death.dm
code/modules/predator/smartdisc.dm

Гиб анимации ставили свои иконки после того как воспроизвелись, в результате чего показывались всрато.
```
:cl:
fix: Исправил анимации гиба и даста.
/:cl:
```

Fixes gib and dust animations.

---

code/modules/xenomorph/acidwell.dm

Теперь в кислотных колодцах постепенно будет появляться кислота

Автозаполнение кислотных колодцев

---

_maps/interiors/apc_cloner.dmm
_maps/map_files/Talos/TGS_Talos.dmm

1. Каргодрон в карго Талоса
2. Лодаут вендор в клонапц

Add loadaut in clone apc and cargo drone AI in Talos

---

code/modules/reqtorio/assembly_crafts.dm

Revert "Update assembly_crafts.dm"

Revert "Update assembly_crafts.dm"

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

Фикс крашера пробегающего сквозь турели

Фикс крашера пробегающего сквозь турели

---

code/modules/reqtorio/assembly_crafts.dm

Очень сильная граната, которая производятся слишком быстро и слишком дёшево.

Нерф производства фосфорок

---

code/modules/mob/mob.dm

double armor

---

code/datums/components/deployable_item.dm
code/game/objects/items.dm
code/modules/projectiles/guns/sentries.dm

Установка турели теперь проверяет только на предмет других турелей.
```
:cl:
fix: Турель теперь проверяет только на предмет других турелей рядом перед установкой.
/:cl:
```

Saner deployable checks for sentries.

---

code/datums/gamemodes/_game_mode.dm
code/datums/round_statistics.dm
code/modules/requisitions/supply_export.dm

порт https://github.com/tgstation/TerraGov-Marine-Corps/pull/16414

Req points from xenos statistics

---

code/datums/components/deployable_item.dm

Adds extra check for sentry placing, to restrict cooperation stacking.

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

урон по кадам и структурам увеличен

Бафф разбега крашера 2

---

code/game/objects/items/scanners.dm

внутренне кровотечение на конечности должно показываться правильно, надеюсь

IB scan fix

---

code/datums/autocells/explosion.dm
code/game/sound.dm
code/modules/mob/living/living.dm
code/modules/mob/living/login.dm
code/modules/mob/living/logout.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm

наверно оптимизирует звуки не могу нормально на локалке посмотреть

playsound optimization

---

code/__DEFINES/objects.dm
code/game/objects/structures/barricade.dm
code/game/objects/structures/razorwire.dm

бафф барикад и проволоки, немного нерфа

Cads buffs

---

code/game/objects/structures/xeno/jelly.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/projectiles/ammo_datums/energy.dm
code/modules/projectiles/ammo_datums/xeno.dm

Желе теперь применяется мгновенно
Строительство стен теперь происходит быстрее и требует меньше плазмы
Керриер теперь немного быстрее, хаггеры (кроме ляврового) прыгают быстрее
КД на желе у дрона уменьшено
Реген плазмы у дрона, ХЛа и ХМа увеличен
У ХМа увеличен пул плазмы
КД на резин глобу у примо ХЛа уменьшено
ХЛ теперь может строить через 2 тайла
Спиттер теперь чуть быстрее бегает и регенит плазму
Луч варлока наносит меньше урона танку и больше урона меху
Глоба байлера наносит больше урона танку и чуть меньше урона меху

Небольшой пак ксеноапов (и два нерфа)

---

_maps/map_files/generic/Admin_Level.dmm
code/game/objects/machinery/OpTable.dm
code/game/objects/machinery/bioprinter.dm
code/game/objects/machinery/buttons.dm
code/game/objects/machinery/computer/Operating.dm
code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending_types.dm

Исправил то что не было метки для ЕОРДА.
Добавил отдел для хирургии, расширил отделы для химии и собирания лодаутов.

Fancy Valhalla.

---

code/controllers/master.dm
code/controllers/subsystem.dm

https://github.com/tgstation/tgstation/pull/81461 порт удобнее профайлить

SSprofiler

---

_maps/map_files/Talos/TGS_Talos.dmm

Повернул 1 декаль, чтобы выглядело красиво.
Все баги, лаги, гриф, набеги и прочая бесовщина была из-за того, что именно эта декаль стояла неправильно.
```
:cl:
fix: Исправил декаль.
/:cl:
```

That shit fix all.

---

code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm

1 -> 2 радиус строительства лорда. Будет строить через клетку. Тестил.

1 -> 2 радиус строительства лорда

---

_maps/map_files/Talos/TGS_Talos.dmm

Покеррума Талоса. С предыдущего ПРа, т.к буры на фобе мы откатываем.

Talos pokerroom

---

_maps/map_files/kutjevo/kutjevo.dmm

Добавил спавн поинты сюрвов на Куджево

fix surv spawn

---

code/modules/reqtorio/machines.dm

Фабрикаторы на корабле теперь требуют поинты что-бы работать, 2 поинта за тик, 64 поинта за стак металла/пороха/металоллома
На земле всё так же бесплатно
Ну и добавлен фабрикатор пластали из другого ПРа

Fabricator nerf v2

---

code/modules/projectiles/ammunition.dm

До:
https://github.com/user-attachments/assets/3ee1f7e6-c327-4fcc-b6a0-db92f2d23aad
После:
https://github.com/user-attachments/assets/5f67fb6a-db52-4fb2-92f0-36df70a889b2
Тикер не будет помирать от такой хуйни.
```
:cl:
code: Массовые взрывы патрон теперь не настолько массовые.
/:cl:
```

Limits ammo explosions.

---

tgui/packages/tgui-panel/chat/ChatPageSettings.jsx
tgui/packages/tgui-panel/chat/ChatTabs.jsx
tgui/packages/tgui-panel/chat/actions.js
tgui/packages/tgui-panel/chat/middleware.js
tgui/packages/tgui-panel/chat/model.js
tgui/packages/tgui-panel/chat/renderer.jsx
tgui/packages/tgui-panel/chat/replaceInTextNode.js
tgui/packages/tgui-panel/settings/SettingsPanel.jsx
tgui/packages/tgui/styles/components/Button.scss

https://github.com/tgstation/tgstation/pull/81354
https://github.com/tgstation/tgstation/pull/82652

Сhat tgui update

---

code/__DEFINES/loadout.dm
code/datums/components/bump_attack.dm
code/game/objects/items/storage/storage.dm
code/game/turfs/liquid_turfs.dm
code/modules/vehicles/armored/__armored.dm

Fixes few runtimes.

---

code/modules/clothing/glasses/glasses.dm
code/modules/clothing/modular_armor/mark_one.dm

Фиксит обходным путём, но все равно нужно.

Fixes identical names of some items, so vending doesn't stack it.

---

code/game/objects/structures/barricade.dm

cads balance

---

code/datums/components/riding/riding_vehicle.dm
code/modules/vehicles/motorbike.dm

Прочность и броня снижены
Теперь требуется время что бы залезть
Коляска немного уменьшает скорость движения

Нерф мотоцикла

---

code/__DEFINES/mobs.dm
code/datums/components/jump.dm
code/modules/mob/living/carbon/update_icons.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

Jump and related fixes

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm

Снижение мили армора равагеру с 50 до 35
Я не знаю, роадмап
Слишком силён против вали рапиры.

Снижение мили армора равагера

---

code/datums/jobs/job/fallen.dm
code/modules/projectiles/projectile.dm

Плевки ксен пролетали мимо, если плевались вплотную к марину

shoulder fire fix

---

code/datums/emergency_calls/clf.dm
code/datums/emergency_calls/icc.dm
code/datums/emergency_calls/sectoid.dm
code/datums/emergency_calls/sons_of_mars_breachers.dm
code/datums/emergency_calls/sonsofmars.dm

Повышает шансы враждебного ЕРТ, если марины побеждают.
В теории маринов будет наказывать если они решили, что эвакуироваться половиной унгаболла - хорошая затея.
```
:cl:
balance: Шансы враждебного ЕРТ теперь выше, если марины побеждают.
/:cl:
```

Increases enemy ert chances if marines are winning.

---

code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm

Урона с руки ранера 21 -> 28.
Часть роадмапы

Раннер мега шиза баф! 21 урона -> 28.

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Меньше времени реакции у морпеха после прямого попадания лярва хагером.

Ап обычных хагеров до остальных, удаление бесполезных переопределений

---

code/modules/projectiles/guns/grenade_launchers.dm

теперь нормал размера
стреляет с одной руки

GL-81 grenade launcher simle buff

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/modularmaps/big_red/bigredatmosvar1.dmm
_maps/modularmaps/big_red/bigredatmosvar2.dmm
_maps/modularmaps/big_red/bigredatmosvar3.dmm
_maps/modularmaps/big_red/bigredatmosvar4.dmm
_maps/modularmaps/big_red/bigredatmosvar5.dmm
_maps/modularmaps/big_red/bigredatmosvar6.dmm
_maps/modularmaps/big_red/bigredlibraryvar1.dmm
_maps/modularmaps/big_red/bigredlibraryvar2.dmm
_maps/modularmaps/big_red/bigredlibraryvar3.dmm
_maps/modularmaps/big_red/bigredtoolshedvar1.dmm
_maps/modularmaps/big_red/bigredtoolshedvar2.dmm
_maps/modularmaps/big_red/bigredtoolshedvar3.dmm
_maps/modularmaps/big_red/bigredtoolshedvar4.dmm
_maps/modularmaps/big_red/bigredtoolshedvar5.dmm

Исправил трубы без выхода ввиде вентиляции.
Исправил то что шкафы в библиотеке не были плотными.
```
:cl:
fix: [Бигред] Исправлены трубы в инженерии, хранилище инструментов и входе в карго.
fix: [Бигред] Исправлены неосязаемые шкафы в библиотеке.
/:cl:
```

Fixes pipenets on Bigred.

---

code/__DEFINES/is_helpers.dm
code/datums/components/deployable_item.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
code/modules/projectiles/gun_system.dm

Добавил по 20 армора, буллет и лазер. Бег бегемота переворачивает турель.
Роадмап
```
:cl:
add: Бегемот переворачивает турели своим бегом.
add: Баф софт армора бегемота, буллет 20->40, лазер 20->40.
balance: Баф бегемота.
code: Добавил в хелпер issentry.
/:cl:
```

Баф бегемота

---

code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm

Шизу не мержить, 21 уже больше чем у половины каст

Revert "Раннер мега шиза баф! 21 урона -> 28."

---

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm

Убрал сило и туман у места спавна диска на Магмуре
Диск теперь не в шести тайлах от тумана. Меньше душки марам.
```
:cl:
map: [Магмур] Сило и туман у диска убраны
/:cl:
```

Change spawn disk Magmoor

---

code/modules/clothing/glasses/glasses.dm

Умом
```
:cl:
fix: Исправил рантайм в коде оранжевых очков.
/:cl:
```

Fixes misusage of update_icon in orange glasses code.

---

code/__HELPERS/unsorted.dm

Наверное поможет с этим. Но пока что в тм-е.
```
:cl:
fix: Исправил то что ошибка для отображения проблемы вызывала еще одну ошибку.
/:cl:
```

Fixes get_angle crash runtimes.

---

code/modules/power/groundmap_geothermal.dm

Скорость починки наземных генераторов скалируется от навыка инженерии
Синты и челы с навыками более полезны
```
:cl:
balance: Скорость починки наземных генераторов скалируется от навыка инженерии
/:cl:
```

improve speed weld geotermal generation

---

code/datums/components/riding/riding_vehicle.dm

Скорость байка апнута
Байк более играбелен. Мы забрали живучесть + дали дилей на залезание, что, в общей сумме, сделало байк неиграбельным из-за снижения скорости с 2.0 до 1.5. Теперь она будет немного повыше.
```
:cl:
balance: Скорость байка с коляской увеличена на 9%
/:cl:
```

Up speed bike with colaska

---

code/game/area/bigred.dm

Fixes bigred underground robotics apc cl test failure.

---

code/datums/jobs/job/marines.dm

теперь у них есть доступ к своему вендору (вендоры там лазерки всякие)
бля можно будет играть
```
:cl:
fix: Боевые роботы снова имеют доступы к своим вендорам.
/:cl:
```

Починил роботам доступы к вендорам

---

code/modules/projectiles/guns/energy.dm

Лаз пистолеты теперь стреляют автоматически.
Не будет нужно использовать кликер, чтобы использовать данный пистолет, он и так говно.
```
:cl:
balance: Лаз пистолеты теперь могут стрелять автоматически.
/:cl:
```

Las pistols are now automatic.

---

code/game/objects/items/explosives/grenades/grenade.dm
code/game/objects/items/explosives/grenades/marines.dm

Deletes grenade useless vars.

---

code/datums/components/suit_autodoc.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/reqs/armor.dm

Модуль Валькирии теперь помимо трико вводит также бикаридин, келотан, гироналин и инапровалин.
Поднял цену в карго с 150 до 200.
Исправил опечатку в сообщении о лечении брута.
Немного почистил код.
Модуль станет полезнее.
```
:cl:
balance: Модуль Валькирии теперь помимо трикордразина вводит бикаридин, келотан, гироналин и инапровалин. 
balance: Цена Модуля Валькирии поднята с 150 до 200.
spellcheck: Исправил опечатку в сообщении модуля автодока о лечении брут урона.
/:cl:
```

Buffs valkyrie module.

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/game/objects/effects/decals/Cleanable/robots.dm
code/game/objects/effects/spawners/gibspawner.dm
code/modules/recycling/disposal.dm

Добавил проверки на маплоад.
```
:cl:
code: Гибы теперь не влияют на скорость загрузки.
/:cl:
```

Optimize gibs mapload.

---

code/__DEFINES/dcs/signals.dm
code/game/atoms/atom_movable.dm
code/game/objects/machinery/squad_supply/supply_beacon.dm
code/game/sound.dm
code/modules/lighting/emissive_blocker.dm
code/modules/mob/dead/dead.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/login.dm
code/modules/mob/living/logout.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm
code/modules/shuttle/on_move.dm

Запортил пр-ы от Люми связанные со звуками, так как там чуть лучше код.
Чуть лучше код, чуть меньше багов.
```
:cl:
fix: Исправил баг с неправильным звучанием различных звуков в танке.
/:cl:
```

Ports playsound changes from offs.

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Маленький багфикс
Багфикс
Исправил неправильный путь у абилки хантера
```
:cl:
fix: Исправил неправильный путь у абилки хантера
/:cl:
```

hunter action fix

---

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

Колодцы теперь нельзя ставить вплотную друг к другу, только через тайл.
Когда Неоморф хватает нож, весь хайв бросает в дрожь.
:cl:
balance: Колодцы теперь нельзя ставить вплотную друг к другу, только через тайл.
/:cl:

Acid unwell

---

code/modules/projectiles/guns/energy.dm

Переключение режима лазпистолета на обычный больше не делает его полуавтоматическим.
```
:cl:
fix: Переключение режима лазпистолета на обычный больше не делает его полуавтоматическим.
/:cl:
```

Fixes laser pistol mode being semiauto while the pistol is fullauto.

---

code/modules/clothing/modular_armor/attachments/storage.dm

В IS pattern Storage module теперь можно ложить материалы.
```
:cl:
fix: В IS pattern Storage module теперь можно ложить материалы.
/:cl:
```

You can now put materials into IS pattern storage module.

---

code/modules/projectiles/attachables/flamer.dm

Снизил до 4 тайлов радиус спрей-насадки
Попытка забалансировать спрей-насадку
```
:cl:
balance: Спрей-насадка теперь прожигает 4 тайла в длину вместо 6
/:cl:
```

Нерф спрей-насадки

---

code/game/area/bigred.dm

Исправил проваливающиеся юнит тесты на Бигреде.
```
:cl:
fix: Исправил проваливающиеся юнит тесты на Бигреде.
/:cl:
```

Fixes unit tests failing on BigRed for real this time.

---

code/game/objects/items/storage/boxes.dm
code/modules/reqs/explosives.dm

Сибиряк покакал, я убрал
я хуй знает
```
:cl:
fix: Исправил гранаты с ТГАЗом в карго
/:cl:
```

Tgas cargofix

---

code/modules/projectiles/projectile.dm

При наводке на человека одной с вами фракции, стрельба через плечо не будет активироваться.
То есть можно будет опять пб-шнуть тиммейта, да.
```
:cl:
fix: При наводке на человека одной с вами фракции, стрельба через плечо не будет активироваться.
/:cl:
```

Shoulder shooting now gives you shoot teammates if they are targeted.

---

code/modules/projectiles/ammo_datums/bullet/rifle.dm
code/modules/projectiles/ammo_datums/bullet/submachinegun.dm

Перегнал урон АП патрон через прогу Ксенона. Немного округлил значения в большую сторону. Для грозы и вектора.
Добавил фаллоу вектору и АРкам
Небольшой ап ХП у Грозы, переигровка статов АП у вектора.
Фаллоу позволит более четко выразить линию того или иного гана, поднимет ценность баррел чарджера(снижает потерю от фаллоу).
Идет вместе с ребалансом хп и армора у беносов.
```
:cl:
balance: Гроза получила 3 фаллоу, ХП 50 урона > 60
balance: АР21 получила 2 фаллоу
balance: Вектор получил 3 фаллоу, АП 15 урона 20 АП > 20 урона 15 АП
/:cl:
```

Rebalance ammo

---

code/modules/mob/living/carbon/xenomorph/embryo.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Хаггера более нельзя будет снять огнем с лица мара, скорость роста лярвы в теле увеличена.
Керриер одна из худших каст, данный ПР это изменит.
```
:cl:
balance: Хаггера более нельзя снять огнем с куклы.
balance: Находящаяся в теле лярва теперь растёт быстрее.
/:cl:
```

Carrier buff

---

code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm

Почистил за собой говно
БАЛАНС
```
:cl:
balance: Spiderling HP 225 -> 150
/:cl:
```

Spiderling HP 225 -> 150

---

code/modules/reqtorio/assembly_crafts.dm

Недочёт
```
:cl:
fix: Исправил то что рецепты для завода требующие стекло, не принимали стекло.
/:cl:
```

Fixes reqtorio crafts that use glass not accepting it as a input.

---

code/modules/reagents/reagents/medical.dm

Изменена скорость метаболизации Окси с 0.25 -> 0.2.
Тоесть с повышенной до стандартной.
1. Для более точной и удобно дозировки хим.реагента с другими типа БККТ-МД и иже с ними.
2. У нас Окси уже давно не бесплатный. Нехай ему иметь еще и повышенный метаболизм. Времена сидения у химдрочки прошли.
```
:cl: Одинокий Аскет
balance: Метаболизация Оксикодона приведена к стандартной.
/:cl:
```

Tweak oxycodone

---

code/__HELPERS/icons.dm
code/__HELPERS/unsorted.dm
code/_globalvars/lists/icons.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/mob_helpers.dm
tgmc.dme

Запортил пару пр-ов с ТГ для лучшей работы `getflaticon()`
Меньше нагрузка.
```
:cl:
code: `getflaticon()` отвечающий за картинки в преф. меню был немного оптимизирован.
/:cl:
```

Getflaticon optimisation

---

code/modules/requisitions/supply_export.dm

Продажа людей в карго теперь приносит очки, как и должно.
Статистика по продаже ксеносов в карго теперь работает.
```
:cl:
fix: Продажа людей в карго теперь приносит очки, как и должно.
fix: Статистика по продаже ксеносов в карго теперь работает.
/:cl:
```

Fixes selling humans now giving any points. Fixes statistics error.

---

code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm

Предлярва теперь может эволюционировать в предалиена.
```
:cl:
fix: Предлярва теперь может эволюционировать в предалиена.
/:cl:
```

Predlarva can now evolve to predalien.

---

code/modules/vehicles/armored/armored_weapons.dm

Танк больше не может выстрелить лишний раз из уже потраченной пули.
```
:cl:
fix: Танк больше не может выстрелить лишний раз из уже потраченной пули.
/:cl:
```

Fixes tank being able to shoot 1 extra time.

---

code/__DEFINES/supply.dm

увеличена цена виндикатора до 1200
запрос баланс системы
```
:cl:
balance: Виндикатора стосит 1200 поинтов
/:cl:
```

Vindicator minigun nerf

---

tgui/packages/tgui-panel/chat/renderer.jsx

Удаляет анимацию возникающую при дупликации сообщений в чате.
Порт https://github.com/ParadiseSS13/Paradise/pull/27292
Посссибл лаг фикс
```
:cl:
code: Удалил анимацию возникающую при дупликации сообщений в чате
/:cl:
```

A possible FPS lag fix caused by chat spam (port)

---

code/_onclick/hud/screen_objects/menu_text_objects.dm

```
:cl:
fix: Исправлен рантайм связанный с кнопкой присоединения в раунд.
/:cl:
```

Fixes join button runtime.

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
code/modules/projectiles/ammo_datums/xeno.dm

кулдаун хедбата уменьшен до 5 сек
трасвитоксовый плевок ретрограда заменён на токсин спит (токс лосс)
менее говёные стрейны
```
:cl:
balance: Кулдаун хедбата уменьшен до 5 сек.
balance: Трасвитоксовый плевок ретрограда заменён на токсин спит.
/:cl:
```

Strains buff

---

_maps/map_files/Talos/TGS_Talos.dmm

Теперь эта херь стоит как надо
Причина тряски?
```
:cl:Basia
fix: В меде пофиксил лампочку. (фикс года)
/:cl:
```

Лютый фикс лампочки в меде

---

code/datums/elements/strippable.dm
code/datums/gamemodes/_game_mode.dm
code/datums/round_statistics.dm
code/modules/mob/living/carbon/human/inventory.dm
code/modules/surgery/organs_internal.dm

Статистика того, сколько раз марины успели снять хаггеров до заражения и того, сколько лярв было удалено хирургически.
Хз.
```
:cl:
add: Добавлена статистика количества проваленных заражений и количества хирургических удалений лярв до бёрста.
/:cl:
```

Hugger statistics

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/client/preferences_gear.dm

Колода карт в оружейном вендоре
Колода карт в оружейном вендоре
Санфорд будет доволен
```
:cl:
add: Колода кард теперь есть в оружейном вендоре и в преф меню
/:cl:
```

Колода карт в оружейном вендоре

---

_maps/map_files/Talos/TGS_Talos.dmm

[Талос] Исправлено то что вентиляция из комнаты танкистов никуда не вела.
```
:cl:
map: [Талос] Исправлено то что вентиляция из комнаты танкистов никуда не вела.
/:cl:
```

Fixes armored vehicle crew bunk vents not leading anywhere.

---

code/game/objects/items/toys/cards.dm

Всё.
Меня разбанит.
```
:cl:Basia
fix: Исправил ошибку со спрайтом коробки Uno
/:cl:
```

Лютый фикс спрайта коробки с Уно

---

code/modules/projectiles/guns/rifles.dm

Добавил бамп-фаер для дмр
увеличивает скорострельность, уменьшает урон, снижает точность (поэтому по ранеру всё мимо летит)
https://github.com/user-attachments/assets/5c4b6a88-763b-43fc-b6e3-bbfb036ebb9b
разнообразие, бафф (возможно), стиль
```
:cl:
add: Добавил бамп-фаер для дмр.
/:cl:
```

DMR fire mods

---

code/game/objects/items/misc.dm

Убрал ненужную херь в коде Коран
Аллах нас всех простит
```
:cl: MrFloppa
fix: В Коран теперь можно ложить все small вещи
/:cl:
```

В Коран теперь можно ложить small вещи

---

code/modules/reagents/reagents/food.dm

```
:cl:
fix: Исправил рантайм связанный с усвоением нутриментов.
/:cl:
```

Fixes nutriment `on_merge` runtime.

---

_maps/interiors/apc_medical.dmm

Изменение внутренней состовляющей мед БТР-а,кроме хирургического стола добавлен слипер,анализатор,ящик роботов.
МЕД БТР станет гораздо полезнее
```
:cl:
balance: Изменил интерьер мед бтр-а. Добавлен слипер, анализатор, ящик для роботов.
/:cl:
```

Adds more medical equipment to medical APC interior.

---

.github/workflows/run_integration_tests.yml

Меньше времени тратиться на какой-то хлам.

Delete redundant sql services.

---

code/datums/storage/subtypes/internal.dm
code/game/objects/items/storage/pouch.dm

Исправил вместимость большого general pouch и ботинок.
```
:cl:
fix: Исправил вместимость большого general pouch и ботинок.
/:cl:
```

Fixes storages of large general pouch and marine shoes.

---

code/modules/clothing/suits/marine_armor.dm
code/modules/projectiles/guns/specialist.dm

Исправил item_flags на садаре, минигане, сг85, б17 и б18
```
:cl:
fix: Исправил item_flags на садаре, минигане, сг85, б17 и б18
/:cl:
```

Fixed item flags on sadar, minigun, sg85,  b17 and b18

---

code/modules/clothing/modular_armor/attachments/uniform.dm

Исправил то что хирургическая разгрузка спавнилась пустой.
```
:cl:
fix: Исправил то что хирургическая разгрузка спавнилась пустой.
/:cl:
```

Fixes surgical webbing contents.

---

code/__DEFINES/loadout/clothes/corpsman.dm
code/datums/storage/subtypes/holster.dm
code/datums/storage/subtypes/internal.dm
code/game/objects/items/storage/backpack.dm
code/game/objects/items/storage/holsters.dm

Исправил вместимость ножен для офицерской сабли, корпсманского сатчела и байка.
```
:cl:
fix: Исправил вместимость ножен для офицерской сабли, корпсманского сатчела и байка.
/:cl:
```

Fixes storages of sabre holster, corpsman satchel and bike.

---

code/controllers/subsystem/vote.dm
code/datums/map_config.dm
code/game/world.dm
code/modules/admin/holder.dm
code/modules/admin/server_verbs.dm
tgui/packages/tgui/interfaces/Vote.jsx

Удалил шип воут и выбор шип карты.
Перевёл оставшиеся админ команды в тгуи.
```
:cl:
del: Удалил шип воут и выбор шип карты.
qol: Перевёл оставшиеся админ команды в тгуи.
/:cl:
```

Deletes ship map vote and change verb. Tgui-fies last admin verbs. 

---

code/datums/storage/storage.dm

Исправил рантайм связанный с стореджами.
```
:cl:
fix: Исправил рантайм связанный с стореджами.
/:cl:
```

Fixes a storage runtime (#17281)

---

code/__DEFINES/xeno.dm

Исправил иконку авто посадки травы.
```
:cl:
fix: Исправил иконку авто посадки травы.
/:cl:
```

Fixes autoweeding action icon.

---

code/modules/mob/mob_verbs.dm

ЕРТ ветеранов теперь спавниться в ЕОРДе.
Больше вариативность.
```
:cl:
add: ЕРТ ветеранов теперь спавниться в ЕОРДе.
/:cl:
```

Adds retired ert to eord spawn pool.

---

code/game/objects/items/power_cells.dm
code/game/objects/items/tools/maintenance_tools.dm
code/game/objects/machinery/cell_charger.dm
code/modules/projectiles/magazines/energy.dm

Батареи для ПНВ теперь нельзя заряжать.
```
:cl:
balance: Батареи для ПНВ теперь нельзя заряжать.
/:cl:
```

Makes nightvision cells properly not rechargable.

---

code/__DEFINES/_subsystems.dm
code/__DEFINES/xeno.dm
code/controllers/subsystem/mobs.dm
code/datums/status_effects/debuffs.dm
code/datums/status_effects/sectoid.dm
code/datums/status_effects/status_effect.dm
code/datums/status_effects/xeno_buffs.dm
code/game/data_huds/xenomorph.dm
code/modules/mob/living/brain/life.dm
code/modules/mob/living/carbon/human/dummy.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
code/modules/mob/living/carbon/xenomorph/life.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living.dm
code/modules/mob/living/silicon/ai/life.dm
code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/friendly/corgi.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/friendly/parrot.dm
code/modules/mob/living/simple_animal/hostile/carp.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/predator/smartdisc.dm

Большинство процессов ксеносов завязанных на тики теперь скалируются от задержки.
Абилка хайвмайнда для возвращения в ядро теперь корректное отображение.
Хайвмайнд теперь имеет корректное отображение худа здоровья.
Лаги вносят меньше импакта против ксеносов.
```
:cl:
fix: Абилка хайвмайнда для возвращения в ядро теперь корректное отображение.
fix: Хайвмайнд теперь имеет корректное отображение худа здоровья.
code: Большинство процессов ксеносов завязанных на тики теперь скалируются от задержки.
/:cl:
```

Delta time healing. Some hivemind fixes.

---

code/__DEFINES/mobs.dm
code/modules/xenomorph/acidwell.dm

Кислотный колодец наполняется только до 3 стадии
Слишком жирно
```
:cl:
balance: Кислотный колодец наполняется только до 3 стадии.
/:cl:
```

Acidwell nerf

---

code/modules/mob/living/carbon/xenomorph/embryo.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Нерф хагеров
Хаги ваги сосать
```
:cl:
balance: Изменён импакт тайм у хагеров.
balance: Время роста лявры увеличено.
/:cl:
```

Huggers nerf

---

code/datums/components/squeak.dm
code/game/objects/items/toys/toys.dm

Плюшевые игрушки более не издают звук при появлении из ящика.
Нельзя положить сервер так просто.
```
:cl:
fix: Плюшевые игрушки более не издают звук при появлении из ящика.
/:cl:
```

Nerfs plush toys ability to kill server.

---

code/modules/client/preferences_toggles.dm

После переключения слышимости админ музыки в преференсах, звук который ты не хочешь слышать обрубается.
Кирк заебал.
```
:cl:
qol: После переключения слышимости админ музыки в преференсах, звук который ты не хочешь слышать обрубается.
/:cl:
```

Toggling off the admin music preference now cuts off the sound.

---

code/game/turfs/floor_ground.dm

Исправил сломанный стейт решетки на Кутьево.
```
:cl:
fix: Исправил сломанный стейт решетки на Кутьево.
/:cl:
```

Fixes kutjevo grate broken state.

---

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm

Луч Кинга больше не проходит сквозь стены, но теперь он может ломать структуры и машинерию.
https://github.com/user-attachments/assets/1c6bd19d-7754-42f9-9b61-838442bb17b6
https://github.com/user-attachments/assets/64a8b590-b52d-43c0-a778-df6a780ee984
Попытка сделать кинга чуть полезнее.
```
:cl:
balance: Луч Кинга больше не проходит сквозь стены, но теперь он может ломать структуры и машинерию.
/:cl:
```

King's Zero Form Beam no longer goes through walls, but damages structures and machinery.

---

code/game/objects/machinery/dropship_part_fabricator.dm

Добавлена переработка снаряжения КАС-а в очки для фабрикатора.
Больше веселья КАС-у.
```
:cl:
add: Добавлена переработка снаряжения КАС-а в очки для фабрикатора.
/:cl:
```

Adds recycling cas equipment to dropship fabricator.

---

code/modules/reqs/supplypacks/weapons.dm

В карго добавлены плазма пушки. Цены взяты с оффов.
Разнообразие.
```
:cl:
add: В карго добавлены плазма пушки.
/:cl:
```

Adds plasma guns to cargo.

---

code/modules/mining/remote_fob/remote_fob_computer.dm

Материалы вытащенные из фоб консоли теперь имеют правильный размер.
Говнокод.
```
:cl:
fix: Материалы вытащенные из фоб консоли теперь имеют правильный размер.
/:cl:
```

Fob console now properly spawns materials when ejected.

---

code/game/objects/items.dm
code/modules/projectiles/attachables/scope.dm
code/modules/vehicles/armored/interiors/chairs.dm

Смотря в бинокль теперь нельзя рулить танком.
```
:cl:
fix: Смотря в бинокль теперь нельзя рулить танком.
/:cl:
```

Fixes being able to use binoculars to snipe from tank.

---

code/modules/projectiles/ammo_datums/energy.dm
code/modules/projectiles/guns/energy.dm

Оверчардж режиму лазерной снайперки добавлено описание.
Исправлено отображение оверчардж режима лазерной снайперки в аммо худе.
```
:cl:
qol: Оверчардж режиму лазерной снайперки добавлено описание.
fix: Исправлено отображение оверчардж режима лазерной снайперки в аммо худе.
/:cl:
```

Adds overcharge sniper mode description, fixes ammo hud state.

---

code/game/objects/items/implants/skill/implant_types.dm

Имплант фаер армс даёт все скилл по владению оружием
мне лень расписывать - https://github.com/PMC-Unga-Marines/Unga-Marines/pull/1041
```
:cl:
balance: Имплант фаер армс даёт все скилл по владению оружием.
/:cl:
```

Firearms implant buff

---

code/datums/components/harvester.dm

В вали можно залить диловен чтобы наносить эффект "микроволновки"
```
:cl:
add: В вали можно залить диловен чтобы наносить эффект "микроволновки".
/:cl:
```

Vali + Dylovene

---

code/modules/projectiles/ammo_datums/bullet/shotgun.dm
code/modules/projectiles/guns/shotguns.dm

Коротко: Стреляет чуть медленнее, урона больше (Но ТТК меньше)
Расширенно: Убрал говнокод патрон к нему, которые на кой-то меняли кучу параметров. Теперь у него ровно такие же боеприпасы, как и у других дробовиков, за исключением уменьшения урона и дебаффов.
Было на 40% меньше урона >>> Стало на 35% меньше
Была скорострельность 0.3 сек >>> Стало 0.4 сек
Была скорость прицеливания 0.8 сек >>> Стало 0.6 сек
Был жуткий фаллофф >>> Теперь он базовый
Меньше страданий от бешенного ТТК в упор (Но это не точно)
```
:cl:
balance: SH46 стреляет медленнее, но улучшен урон и дальность.
/:cl:
```

SH46 Balance

---

code/modules/projectiles/ammo_datums/bullet/submachinegun.dm

смг ап патроны нельзя восстанавливать через материю.
меня убили я пошёл нерфить <details>
<summary>ЫЫЫЫ</summary>
В импорте есть не ап патроны))
</details>
```
:cl:
add: смг ап патроны нельзя восстанавливать через материю.
/:cl:
```

smg bullet life matters

---

code/modules/admin/topic.dm

Теперь в админской менюшке тгуи инпуты
Удобно искать. Там итак что-то вводилось через тгуи, так чего же остальное на него не перевести?
```
:cl:
admin: В меню Rank and Equipment теперь тгуи ввод.
/:cl:
```

Rank and Equipment tgui input

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm

Повысил макс хп равагера с 350 до 450.
Терпила станет терпеливее.
```
:cl:
balance: Повысил макс хп равагера с 350 до 450.
/:cl:
```

Raises ravager max health from 350 to 450.

---

code/modules/projectiles/ammo_datums/bullet/sniper.dm

Смотри ченджлог.
Не ломается спрайт из-за большего количества пуль в горсти, чем позволяет спрайт.
```
:cl:
fix: Теперь горсти патрон к ПТРД вмещают максимум 5 пуль.
/:cl:
```

Fixed PTRD ammo handfuls

---

code/controllers/subsystem/persistence.dm

добавялет новый сезон тяжелого оружия
будет больше тяжелого оружия в ранней игре
```
:cl:
add: Добавил сезон тяжелого оружия.
/:cl:
```

Сезон тяжелого оружия

---

code/datums/gamemodes/distress.dm
code/datums/jobs/job/shipside.dm

Танка не будет на лоу попе
да
```
:cl:
balance: Роль танкистов теперь появляется только от 35 очков работы (приблизительно столько же онлайна).
/:cl:
```

Restricts assault crewman behind 35 job points.

---

code/datums/gamemodes/zombie_crash.dm

Исправлено бесконечное появление зомби
Исправлено бесконечное появление зомби
```
:cl:
fix: Исправлено бесконечное появление зомби
/:cl:
```

Fix zombie crash infinite spawning

---

code/_onclick/hud/ghost.dm
code/_onclick/hud/new_player.dm
code/_onclick/hud/rendering/_plane_master.dm
code/_onclick/hud/screen_objects/screen_objects.dm
code/game/objects/items/devices/minimap_tablet.dm
code/game/objects/machinery/cic_maptable.dm
code/modules/buildmode/buildmode.dm
code/modules/buildmode/buttons.dm
code/modules/mob/living/silicon/ai/multicam.dm

Исправил харддел `hud/new_player`.
```
:cl:
fix: Исправил harddel от hud/new_player.
/:cl:
```

Fixes hud/new_player harddel.

---

code/modules/vehicles/motorbike.dm

Исправил баллун алёрт в проверке байка на пассажиров при посадке.
```
:cl:
fix: Исправил баллун алёрт в проверке байка на пассажиров при посадке.
/:cl:
```

Fixes balloon alert in motorbike occupants check.

---

code/__DEFINES/colors.dm
code/datums/chatmessage.dm
code/datums/jobs/squads.dm

Цвет рунчата теперь зависит от цвета сквада игрока
как на цмах да... сквадная культура
```
:cl:
add: Цвет рунчата теперь зависит от цвета сквада игрока
/:cl:
```

Squad colors

---

code/datums/storage/subtypes/box.dm
code/datums/storage/subtypes/internal.dm
code/modules/projectiles/magazines/energy.dm

ТЕ паверпак на спину теперь нельзя положить в разгрузку.
Плазма батарейки теперь нельзя заряжать от паверпаков.
```
:cl:
fix: ТЕ паверпак на спину теперь нельзя положить в разгрузку.
fix: Плазма батарейки теперь нельзя заряжать от паверпаков.
/:cl:
```

You can no longer recharge plasma cells with te powerpacks. TE back powerpack no longer fits in webbing.
